// =====================================================
// CORRUPTÓMETRO MX — BASE DE DATOS NACIONAL
// Fuentes: OSFEM, SCJN, TEPJF, ASF, SESNSP, SHCP,
// Proceso, El Universal, Infobae, La Jornada, Milenio
// Última actualización: Julio 2026
// =====================================================

const SCORING_CRITERIA = [
    { id: 'sentencias', label: 'Sentencias o procesos penales', maxPoints: 25, desc: 'Condenas, consignaciones o procesos penales activos' },
    { id: 'fiscalizacion', label: 'Observaciones de fiscalización', maxPoints: 20, desc: 'Hallazgos de OSFEM, ASF o auditorías con montos no comprobados' },
    { id: 'funcionarios', label: 'Funcionarios detenidos / red', maxPoints: 15, desc: 'Colaboradores directos detenidos o red criminal documentada' },
    { id: 'deuda', label: 'Deuda / daño patrimonial', maxPoints: 15, desc: 'Desvío de recursos, peculado o daño al erario documentado' },
    { id: 'denuncias', label: 'Denuncias documentadas', maxPoints: 10, desc: 'Denuncias ciudadanas, periodísticas o de organismos verificadas' },
    { id: 'evasion', label: 'Evasión de justicia / desacato', maxPoints: 10, desc: 'Amparos para evadir detención, fuga, desacato judicial' },
    { id: 'nepotismo', label: 'Nepotismo / conflicto de interés', maxPoints: 5, desc: 'Concesiones irregulares, familiares en nómina, contratos dirigidos' },
];

const officials = [
    // =====================================================
    // EXGOBERNADORES — NIVEL ESTATAL / FEDERAL
    // =====================================================
    {
        id: 101,
        name: 'Javier Duarte de Ochoa',
        role: 'Exgobernador de Veracruz (2010-2016)',
        party: 'PRI',
        state: 'Veracruz',
        level: 'estatal',
        active: false,
        scores: { sentencias: 25, fiscalizacion: 20, funcionarios: 14, deuda: 15, denuncias: 10, evasion: 10, nepotismo: 4 },
        breakdown: {
            sentencias: 'Sentenciado a 9 años por asociación delictuosa y lavado de dinero. Vinculado a nuevo proceso en 2026 por desvío de $5M. Detenido en Guatemala en 2017.',
            fiscalizacion: 'ASF documentó desvíos masivos del erario veracruzano. Desaparición de recursos del sistema de salud estatal.',
            funcionarios: 'Múltiples excolaboradores detenidos y procesados. Red de corrupción sistémica en el gobierno estatal.',
            deuda: 'Daño al erario estimado en miles de millones. Desvío de recursos de programas de salud, educación e infraestructura.',
            denuncias: 'Caso ampliamente documentado por medios nacionales e internacionales. Denuncias de familiares de desaparecidos.',
            evasion: 'Prófugo durante 6 meses. Capturado en Guatemala. Jueza negó libertad anticipada en noviembre 2025 pese a cumplir 95% de condena.',
            nepotismo: 'Empresas fantasma vinculadas a su círculo. Propiedades a nombre de prestanombres.',
        },
        timeline: [
            { year: '2010', event: 'Asume gubernatura de Veracruz' },
            { year: '2016', event: 'Solicita licencia 20 días antes de terminar mandato. Se fuga.' },
            { year: '2017', event: 'Capturado en Guatemala. Extraditado a México.' },
            { year: '2018', event: 'Sentenciado a 9 años de prisión' },
            { year: '2025', event: 'Jueza niega libertad anticipada' },
            { year: '2026', event: 'Vinculado a nuevo proceso por desvío adicional' },
        ],
        sources: [
            { label: 'Proceso — Captura', url: 'https://www.proceso.com.mx' },
            { label: 'Infobae — Sentencia', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 102,
        name: 'César Duarte Jáquez',
        role: 'Exgobernador de Chihuahua (2010-2016)',
        party: 'PRI',
        state: 'Chihuahua',
        level: 'estatal',
        active: false,
        scores: { sentencias: 23, fiscalizacion: 20, funcionarios: 13, deuda: 15, denuncias: 9, evasion: 8, nepotismo: 4 },
        breakdown: {
            sentencias: 'Preso en el Altiplano. Acusado de lavado de dinero por más de $73M. Ficha roja de Interpol.',
            fiscalizacion: 'Red de corrupción que generó daños al erario por $6,000M según autoridades de Chihuahua.',
            funcionarios: 'Entre 50 y 80 amparos tramitados por excolaboradores para evitar detención.',
            deuda: 'Desvío estimado en $6,000 millones de pesos del erario chihuahuense.',
            denuncias: 'Documentado extensamente. Múltiples denuncias de la administración sucesora.',
            evasion: 'Prófugo con ficha roja de Interpol. Detenido en EE.UU. y extraditado.',
            nepotismo: 'Red de prestanombres y empresas fantasma documentada.',
        },
        timeline: [
            { year: '2010', event: 'Asume gubernatura de Chihuahua' },
            { year: '2016', event: 'Termina mandato. Huye del país.' },
            { year: '2020', event: 'Detenido en Estados Unidos' },
            { year: '2023', event: 'Extraditado a México. Internado en penal del Altiplano.' },
        ],
        sources: [
            { label: 'Reforma — Detención', url: 'https://www.reforma.com' },
            { label: 'El Universal — Proceso', url: 'https://www.eluniversal.com.mx' },
        ],
    },
    {
        id: 103,
        name: 'Roberto Borge Angulo',
        role: 'Exgobernador de Quintana Roo (2011-2016)',
        party: 'PRI',
        state: 'Quintana Roo',
        level: 'estatal',
        active: false,
        scores: { sentencias: 21, fiscalizacion: 17, funcionarios: 10, deuda: 13, denuncias: 8, evasion: 8, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido en Panamá en 2017. Procesado por lavado de dinero y delincuencia organizada. Absuelto de delincuencia organizada en 2026; continúa proceso bajo prisión domiciliaria.',
            fiscalizacion: 'Venta irregular de terrenos públicos de Quintana Roo a precios por debajo del mercado.',
            funcionarios: 'Red de funcionarios involucrados en operaciones inmobiliarias irregulares.',
            deuda: 'Daño patrimonial por venta de predios estatales. Operaciones con recursos de procedencia ilícita.',
            denuncias: 'Denunciado por la administración sucesora y organizaciones ciudadanas.',
            evasion: 'Prófugo. Capturado en Panamá y deportado a México.',
            nepotismo: 'Benefició a allegados con ventas de terrenos públicos a precios preferenciales.',
        },
        timeline: [
            { year: '2011', event: 'Asume gubernatura de Quintana Roo' },
            { year: '2017', event: 'Detenido en Panamá. Deportado a México.' },
            { year: '2026', event: 'Absuelto de delincuencia organizada. Prisión domiciliaria con brazalete.' },
        ],
        sources: [
            { label: 'La Verdad Noticias', url: 'https://laverdadnoticias.com' },
        ],
    },
    {
        id: 104,
        name: 'Tomás Yarrington Ruvalcaba',
        role: 'Exgobernador de Tamaulipas (1999-2005)',
        party: 'PRI',
        state: 'Tamaulipas',
        level: 'estatal',
        active: false,
        scores: { sentencias: 24, fiscalizacion: 15, funcionarios: 12, deuda: 14, denuncias: 10, evasion: 9, nepotismo: 3 },
        breakdown: {
            sentencias: 'Procesado en EE.UU. por lavado de dinero y vínculos con narcotráfico. Orden de aprehensión desde 2012.',
            fiscalizacion: 'Acusaciones de recibir sobornos del crimen organizado durante su mandato.',
            funcionarios: 'Investigaciones contra red de exfuncionarios tamaulipecos.',
            deuda: 'Lavado de dinero por millones de dólares a través de propiedades en Texas.',
            denuncias: 'Caso documentado por la DEA y autoridades de EE.UU.',
            evasion: 'Prófugo durante años. Detenido en Italia en 2017.',
            nepotismo: 'Propiedades en EE.UU. a nombre de prestanombres.',
        },
        timeline: [
            { year: '1999', event: 'Asume gubernatura de Tamaulipas' },
            { year: '2012', event: 'Orden de aprehensión emitida' },
            { year: '2017', event: 'Detenido en Italia' },
        ],
        sources: [
            { label: 'Proceso — Detención', url: 'https://www.proceso.com.mx' },
        ],
    },
    {
        id: 105,
        name: 'Eugenio Hernández Flores',
        role: 'Exgobernador de Tamaulipas (2005-2010)',
        party: 'PRI',
        state: 'Tamaulipas',
        level: 'estatal',
        active: false,
        scores: { sentencias: 22, fiscalizacion: 14, funcionarios: 10, deuda: 13, denuncias: 8, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido en 2017. Procesado por lavado de dinero y vínculos con narcotráfico.',
            fiscalizacion: 'Señalamientos de desvío de recursos durante su administración.',
            funcionarios: 'Exfuncionarios investigados por vínculos con el crimen organizado.',
            deuda: 'Recursos de procedencia ilícita canalizados a través de empresas.',
            denuncias: 'Investigaciones de la PGR y DEA.',
            evasion: 'Mantuvo perfil bajo antes de su detención.',
            nepotismo: 'Red de prestanombres documentada.',
        },
        timeline: [
            { year: '2005', event: 'Asume gubernatura de Tamaulipas' },
            { year: '2017', event: 'Detenido por autoridades federales' },
        ],
        sources: [
            { label: 'Milenio — Detención', url: 'https://www.milenio.com' },
        ],
    },
    {
        id: 106,
        name: 'Roberto Sandoval Castañeda',
        role: 'Exgobernador de Nayarit (2011-2017)',
        party: 'PRI',
        state: 'Nayarit',
        level: 'estatal',
        active: false,
        scores: { sentencias: 23, fiscalizacion: 18, funcionarios: 11, deuda: 14, denuncias: 9, evasion: 5, nepotismo: 4 },
        breakdown: {
            sentencias: 'Sentenciado por falsificación de documentos. Preso en CEFERESO No. 4 desde 2021. Enfrenta cargos adicionales por lavado de dinero, enriquecimiento ilícito y asociación delictuosa.',
            fiscalizacion: 'Juicio político aprobado por desvío de $2,700M del erario nayarita.',
            funcionarios: 'Red de funcionarios involucrados en desvíos documentada.',
            deuda: 'Desvío estimado en $2,700 millones de pesos. Enriquecimiento ilícito.',
            denuncias: 'Ciudadanos documentaron en expedientes: desvío de recursos, violaciones a la Constitución estatal.',
            evasion: 'No logró evadir la justicia efectivamente.',
            nepotismo: 'Propiedades irregulares, incluida una en San Blas obtenida con documentos falsificados.',
        },
        timeline: [
            { year: '2011', event: 'Asume gubernatura de Nayarit' },
            { year: '2018', event: 'Congreso aprueba juicio político por desvío de $2,700M' },
            { year: '2021', event: 'Preso en CEFERESO No. 4' },
            { year: '2025', event: 'Sentenciado por falsificación de documentos' },
        ],
        sources: [
            { label: 'El Informador — Sentencia', url: 'https://www.informador.mx' },
        ],
    },
    {
        id: 107,
        name: 'Mario Marín Torres',
        role: 'Exgobernador de Puebla (2005-2011)',
        party: 'PRI',
        state: 'Puebla',
        level: 'estatal',
        active: false,
        scores: { sentencias: 22, fiscalizacion: 10, funcionarios: 8, deuda: 8, denuncias: 10, evasion: 6, nepotismo: 3 },
        breakdown: {
            sentencias: 'Preso. Regresó al penal del Altiplano en abril 2025 tras revocación de prisión domiciliaria. Procesado por tortura contra la periodista Lydia Cacho.',
            fiscalizacion: 'Señalamientos de uso irregular de recursos públicos.',
            funcionarios: 'Caso vinculado a red de protección a Kamel Nacif (empresario).',
            deuda: 'Uso de aparato estatal para perseguir periodistas y proteger intereses privados.',
            denuncias: 'Caso Lydia Cacho ampliamente documentado nacional e internacionalmente. Grabaciones telefónicas lo implican directamente.',
            evasion: 'Prófugo antes de ser detenido. Gozó de prisión domiciliaria hasta su revocación.',
            nepotismo: 'Relación documentada con empresario Kamel Nacif para protección mutua.',
        },
        timeline: [
            { year: '2005', event: 'Asume gubernatura de Puebla' },
            { year: '2005', event: 'Caso Lydia Cacho: grabaciones lo implican en tortura a periodista' },
            { year: '2021', event: 'Detenido tras años de investigación' },
            { year: '2025', event: 'Regresa al penal del Altiplano tras revocación de prisión domiciliaria' },
        ],
        sources: [
            { label: 'La Verdad Noticias', url: 'https://laverdadnoticias.com' },
        ],
    },
    {
        id: 108,
        name: 'Jaime Rodríguez Calderón "El Bronco"',
        role: 'Exgobernador de Nuevo León (2015-2021)',
        party: 'Independiente',
        state: 'Nuevo León',
        level: 'estatal',
        active: false,
        scores: { sentencias: 20, fiscalizacion: 14, funcionarios: 6, deuda: 10, denuncias: 8, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Preso en CERESO de Apodaca. Acusado de desvío de recursos públicos y lavado de dinero durante campaña presidencial 2018.',
            fiscalizacion: 'Investigado por uso de recursos públicos para financiar campaña presidencial.',
            funcionarios: 'Excolaboradores investigados por participación en irregularidades de campaña.',
            deuda: 'Desvío de recursos públicos estatales para fines electorales.',
            denuncias: 'Documentado por medios y autoridades electorales.',
            evasion: 'No evadió efectivamente la justicia.',
            nepotismo: 'Uso de estructura gubernamental para fines personales.',
        },
        timeline: [
            { year: '2015', event: 'Gana gubernatura como candidato independiente' },
            { year: '2018', event: 'Se postula a la presidencia. Irregularidades en campaña.' },
            { year: '2022', event: 'Detenido e ingresado a CERESO de Apodaca' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 109,
        name: 'Andrés Granier Melo',
        role: 'Exgobernador de Tabasco (2007-2012)',
        party: 'PRI',
        state: 'Tabasco',
        level: 'estatal',
        active: false,
        scores: { sentencias: 18, fiscalizacion: 17, funcionarios: 7, deuda: 14, denuncias: 8, evasion: 4, nepotismo: 4 },
        breakdown: {
            sentencias: 'Condenado a 10 años 10 meses por peculado. Sentencia revocada en 2019 tras 5 años y medio preso. Liberado.',
            fiscalizacion: 'Desvío de $196.9M del Seguro Popular documentado por auditorías.',
            funcionarios: 'Funcionarios de salud involucrados en desvío del Seguro Popular.',
            deuda: 'Peculado por $196.9 millones de pesos del programa Seguro Popular.',
            denuncias: 'Caso mediático: pijamas italianas, lujos en prisión documentados por medios.',
            evasion: 'No evadió la justicia pero gozó de privilegios en prisión.',
            nepotismo: 'Estilo de vida ostentoso incompatible con salario público.',
        },
        timeline: [
            { year: '2007', event: 'Asume gubernatura de Tabasco' },
            { year: '2013', event: 'Detenido por peculado' },
            { year: '2019', event: 'Sentencia revocada. Liberado tras 5.5 años preso.' },
        ],
        sources: [
            { label: 'Infobae — Caso', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 110,
        name: 'Rodrigo Medina de la Cruz',
        role: 'Exgobernador de Nuevo León (2009-2015)',
        party: 'PRI',
        state: 'Nuevo León',
        level: 'estatal',
        active: false,
        scores: { sentencias: 14, fiscalizacion: 14, funcionarios: 5, deuda: 11, denuncias: 7, evasion: 5, nepotismo: 3 },
        breakdown: {
            sentencias: 'Vinculado a proceso por ejercicio indebido de funciones públicas. Enfrentó proceso en libertad. Exonerado en 2018.',
            fiscalizacion: 'Presuntas irregularidades en incentivos a la armadora KIA Motors.',
            funcionarios: 'Investigaciones contra exfuncionarios de su administración.',
            deuda: 'Peculado y daño patrimonial señalados. Preso en Topo Chico brevemente.',
            denuncias: 'Caso KIA Motors documentado por medios nacionales.',
            evasion: 'Amparos utilizados para enfrentar proceso en libertad.',
            nepotismo: 'Incentivos fiscales cuestionados a empresa automotriz.',
        },
        timeline: [
            { year: '2009', event: 'Asume gubernatura de Nuevo León' },
            { year: '2016', event: 'Vinculado a proceso por caso KIA' },
            { year: '2018', event: 'Exonerado tras proceso' },
        ],
        sources: [
            { label: 'Alcaldes de México', url: 'https://www.alcaldesdemexico.com' },
        ],
    },
    {
        id: 111,
        name: 'Mario Villanueva Madrid',
        role: 'Exgobernador de Quintana Roo (1993-1999)',
        party: 'PRI',
        state: 'Quintana Roo',
        level: 'estatal',
        active: false,
        scores: { sentencias: 25, fiscalizacion: 12, funcionarios: 8, deuda: 12, denuncias: 9, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sentenciado en 2020 por delitos contra la salud. 19 años en prisión. Actualmente en arresto domiciliario desde 2020 por edad y condiciones médicas.',
            fiscalizacion: 'Procesado por vínculos con narcotráfico durante su mandato.',
            funcionarios: 'Colaboradores involucrados en red de protección al narcotráfico.',
            deuda: 'Recursos de procedencia ilícita por protección a cárteles.',
            denuncias: 'Investigado por autoridades mexicanas y estadounidenses.',
            evasion: 'Prófugo antes de su captura. 19 años preso.',
            nepotismo: 'Red de protección al crimen organizado desde la gubernatura.',
        },
        timeline: [
            { year: '1993', event: 'Asume gubernatura de Quintana Roo' },
            { year: '2001', event: 'Detenido' },
            { year: '2020', event: 'Arresto domiciliario tras 19 años preso' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 112,
        name: 'Rubén Rocha Moya',
        role: 'Gobernador de Sinaloa (2021-presente)',
        party: 'MORENA',
        state: 'Sinaloa',
        level: 'estatal',
        active: true,
        scores: { sentencias: 10, fiscalizacion: 8, funcionarios: 5, deuda: 5, denuncias: 10, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Acusado por EE.UU. de vínculos con narcotráfico. FGR inició investigación. Sin sentencia ni orden de aprehensión hasta la fecha.',
            fiscalizacion: 'Bajo investigación. Sin hallazgos formales publicados aún.',
            funcionarios: 'Crisis de seguridad en Sinaloa con enfrentamientos entre facciones del Cártel de Sinaloa.',
            deuda: 'Sin documentación de daño patrimonial directo hasta ahora.',
            denuncias: 'Acusación de EE.UU. con alto impacto mediático. Investigación de FGR abierta.',
            evasion: 'Defiende su inocencia. No ha evadido proceso.',
            nepotismo: 'Señalamientos de cercanía con figuras del crimen organizado.',
        },
        timeline: [
            { year: '2021', event: 'Asume gubernatura de Sinaloa' },
            { year: '2024', event: 'Crisis de seguridad en Culiacán tras captura de Zambada' },
            { year: '2026', event: 'EE.UU. lo acusa de vínculos con narcotráfico. FGR investiga.' },
        ],
        sources: [
            { label: 'El Siglo de Torreón', url: 'https://www.elsiglodetorreon.com.mx' },
        ],
    },
    {
        id: 113,
        name: 'Ricardo Gallardo Cardona',
        role: 'Gobernador de San Luis Potosí (2021-presente)',
        party: 'PVEM',
        state: 'San Luis Potosí',
        level: 'estatal',
        active: true,
        scores: { sentencias: 12, fiscalizacion: 10, funcionarios: 5, deuda: 6, denuncias: 8, evasion: 4, nepotismo: 4 },
        breakdown: {
            sentencias: 'Estuvo preso en 2015. Antecedentes penales previos a la gubernatura. Bajo escrutinio por presuntas irregularidades.',
            fiscalizacion: 'Señalamientos de manejo opaco de recursos estatales.',
            funcionarios: 'Investigaciones contra miembros de su administración.',
            deuda: 'Cuestionamientos sobre licitaciones y contratos.',
            denuncias: 'Medios nacionales y organizaciones civiles han documentado señalamientos.',
            evasion: 'Antecedentes penales pero logró postularse y ganar gubernatura.',
            nepotismo: 'Señalamientos de concentración de poder y contratos dirigidos.',
        },
        timeline: [
            { year: '2015', event: 'Estuvo preso por cargos penales' },
            { year: '2021', event: 'Gana gubernatura por el PVEM' },
        ],
        sources: [
            { label: 'Polls MX — Análisis', url: 'https://polls.politico.mx' },
        ],
    },
    {
        id: 114,
        name: 'Luis Armando Reynoso Femat',
        role: 'Exgobernador de Aguascalientes (2004-2010)',
        party: 'PAN',
        state: 'Aguascalientes',
        level: 'estatal',
        active: false,
        scores: { sentencias: 16, fiscalizacion: 14, funcionarios: 4, deuda: 9, denuncias: 6, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Declarado culpable de ejercicio indebido del servicio público y peculado por $13.8M. Sentenciado a 2 años 9 meses (pagó pena en libertad por ser menor a 5 años).',
            fiscalizacion: 'Fingió adquisición de tomógrafo computarizado para el Instituto de Salud estatal.',
            funcionarios: 'Funcionarios de salud involucrados en compra ficticia.',
            deuda: 'Peculado por $13.8M del erario de Aguascalientes.',
            denuncias: 'Documentado por medios y autoridades judiciales.',
            evasion: 'Amparos para enfrentar proceso. Pena pagada en libertad.',
            nepotismo: 'Adquisición ficticia de equipo médico.',
        },
        timeline: [
            { year: '2004', event: 'Asume gubernatura de Aguascalientes' },
            { year: '2019', event: 'Declarado culpable por peculado y ejercicio indebido' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 115,
        name: 'Flavino Ríos Alvarado',
        role: 'Exgobernador interino de Veracruz (2016)',
        party: 'PRI',
        state: 'Veracruz',
        level: 'estatal',
        active: false,
        scores: { sentencias: 18, fiscalizacion: 8, funcionarios: 4, deuda: 6, denuncias: 7, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Procesado por encubrimiento. Facilitó la fuga de Javier Duarte al concederle licencia como gobernador.',
            fiscalizacion: 'Señalado por facilitar la impunidad de su antecesor.',
            funcionarios: 'Complicidad documentada con la red de Duarte.',
            deuda: 'Complicidad en encubrimiento, no desvío directo documentado.',
            denuncias: 'Medios documentaron su papel en facilitar la fuga de Duarte.',
            evasion: 'Enfrentó proceso judicial.',
            nepotismo: 'Lealtad política sobre legalidad al facilitar licencia de Duarte.',
        },
        timeline: [
            { year: '2016', event: 'Asume interinato de Veracruz. Facilita licencia a Duarte.' },
            { year: '2017', event: 'Procesado por encubrimiento' },
        ],
        sources: [
            { label: 'Alcaldes de México', url: 'https://www.alcaldesdemexico.com' },
        ],
    },
    {
        id: 116,
        name: 'Jorge Torres López',
        role: 'Exgobernador interino de Coahuila (2011)',
        party: 'PRI',
        state: 'Coahuila',
        level: 'estatal',
        active: false,
        scores: { sentencias: 20, fiscalizacion: 14, funcionarios: 6, deuda: 12, denuncias: 8, evasion: 10, nepotismo: 3 },
        breakdown: {
            sentencias: 'Acusado por la DEA de conspiración para lavado de dinero. En la lista de "fugitivos más buscados" desde 2016.',
            fiscalizacion: 'Depositó fondos saqueados del erario de Coahuila en paraísos fiscales y bancos de Texas.',
            funcionarios: 'Red vinculada al exgobernador Humberto Moreira.',
            deuda: 'Saqueo del erario coahuilense canalizado a cuentas en el extranjero.',
            denuncias: 'Investigaciones de la DEA y autoridades de EE.UU.',
            evasion: 'PRÓFUGO. En lista de fugitivos más buscados de la DEA desde 2016.',
            nepotismo: 'Red de lavado de dinero transnacional.',
        },
        timeline: [
            { year: '2011', event: 'Gobernador interino de Coahuila en sustitución de Moreira' },
            { year: '2016', event: 'DEA lo declara fugitivo. Paradero desconocido.' },
        ],
        sources: [
            { label: 'Proceso — DEA', url: 'https://www.proceso.com.mx' },
        ],
    },
    // =====================================================
    // OPERACIÓN ENJAMBRE — MUNICIPALES
    // =====================================================
    {
        id: 201,
        name: 'María Elena Martínez Robles',
        role: 'Expresidenta Municipal de Amanalco, EdoMex',
        party: 'MC/MORENA',
        state: 'Estado de México',
        level: 'municipal',
        active: false,
        scores: { sentencias: 25, fiscalizacion: 8, funcionarios: 10, deuda: 5, denuncias: 9, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sentenciada a 70 AÑOS de prisión por homicidio calificado. Ordenó asesinato del síndico municipal y su chofer en enero 2023.',
            fiscalizacion: 'Señalamientos de uso irregular de recursos municipales.',
            funcionarios: 'Coordinó con integrantes de La Familia Michoacana para mantener control político.',
            deuda: 'No documentado específicamente.',
            denuncias: 'Caso documentado por FGJEM. Operación Enjambre.',
            evasion: 'Detenida en noviembre 2024.',
            nepotismo: 'Control político absoluto del municipio mediante intimidación.',
        },
        timeline: [
            { year: '2022', event: 'Asume presidencia municipal. Se afilia a Morena.' },
            { year: '2023', event: 'Ordena asesinato del síndico municipal y chofer' },
            { year: '2024', event: 'Detenida en Operación Enjambre' },
            { year: '2025', event: 'Sentenciada a 70 años de prisión' },
        ],
        sources: [
            { label: 'El Financiero — Enjambre', url: 'https://www.elfinanciero.com.mx' },
            { label: 'Telediario — Sentencia', url: 'https://www.telediario.mx' },
        ],
    },
    {
        id: 202,
        name: 'Diego Rivera Navarro',
        role: 'Presidente Municipal de Tequila, Jalisco',
        party: 'MC',
        state: 'Jalisco',
        level: 'municipal',
        active: false,
        scores: { sentencias: 22, fiscalizacion: 12, funcionarios: 14, deuda: 8, denuncias: 9, evasion: 3, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido el 5 de febrero 2026. Prisión preventiva oficiosa en Almoloya de Juárez por extorsión y vínculos con CJNG.',
            fiscalizacion: 'Esquema de extorsión sistemática desde oficinas gubernamentales.',
            funcionarios: 'Detenido junto con director de Padrón y Licencias, Tesorería, Catastro y Obras Públicas. Todos vinculados a esquema de extorsión para el CJNG.',
            deuda: 'Recursos obtenidos mediante extorsión entregados al CJNG a través de intermediario "El Rey Mago".',
            denuncias: 'Denuncias de empresarios cerveceros y tequileros extorsionados.',
            evasion: 'No logró evadir detención.',
            nepotismo: 'Funcionarios de primer círculo como operadores del esquema criminal.',
        },
        timeline: [
            { year: '2024', event: 'Secuestro de candidatos opositores durante campaña electoral' },
            { year: '2025', event: 'Asume presidencia municipal de Tequila' },
            { year: '2026', event: 'Detenido en Operación Enjambre junto con 4 funcionarios' },
        ],
        sources: [
            { label: 'Infobae — Enjambre Jalisco', url: 'https://www.infobae.com' },
            { label: 'SinEmbargo — Detención', url: 'https://www.sinembargo.mx' },
        ],
    },
    {
        id: 203,
        name: 'Agustín Toledano Amaro',
        role: 'Presidente Municipal de Atlatlahucan, Morelos',
        party: 'PAN',
        state: 'Morelos',
        level: 'municipal',
        active: false,
        scores: { sentencias: 18, fiscalizacion: 8, funcionarios: 8, deuda: 6, denuncias: 9, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido el 20 de mayo 2026 por presuntos delitos de extorsión y delincuencia organizada.',
            fiscalizacion: 'Investigación por desvío de recursos municipales hacia red criminal.',
            funcionarios: 'Aparece en video con presuntos integrantes del crimen organizado.',
            deuda: 'Financiamiento irregular de campañas electorales señalado.',
            denuncias: 'Denuncias ciudadanas por extorsión. Video lo vincula con criminales.',
            evasion: 'Promovió amparo contra orden de aprehensión (desechado parcialmente).',
            nepotismo: 'Vínculos con exgobernador Marco Adame Castillo.',
        },
        timeline: [
            { year: '2025', event: 'Asume presidencia municipal por coalición PAN-PRI-PRD' },
            { year: '2025', event: 'Aparece en video con presuntos criminales' },
            { year: '2026', event: 'Detenido en Operación Enjambre' },
        ],
        sources: [
            { label: 'Expansión — Morelos', url: 'https://politica.expansion.mx' },
        ],
    },
    {
        id: 204,
        name: 'Irving Sánchez Zavala',
        role: 'Exalcalde de Yecapixtla, Morelos',
        party: 'MORENA',
        state: 'Morelos',
        level: 'municipal',
        active: false,
        scores: { sentencias: 17, fiscalizacion: 7, funcionarios: 6, deuda: 6, denuncias: 8, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido en mayo 2026. Acusado de formar parte de estructura política que permitió financiamiento criminal de campañas.',
            fiscalizacion: 'Investigación por vínculos con red de corrupción.',
            funcionarios: 'Parte de red de funcionarios detenidos en Morelos.',
            deuda: 'Presunto financiamiento de campaña por el crimen organizado.',
            denuncias: 'FGR reveló vínculos con homicidio de expresidentes municipales y financiamiento criminal.',
            evasion: 'No evadió la justicia.',
            nepotismo: 'Red política-criminal en la región.',
        },
        timeline: [
            { year: '2026', event: 'Detenido en Operación Enjambre en Morelos' },
        ],
        sources: [
            { label: 'Expansión — Detención', url: 'https://politica.expansion.mx' },
        ],
    },
    {
        id: 205,
        name: 'Jesús Corona Damián',
        role: 'Alcalde de Cuautla, Morelos',
        party: 'MORENA',
        state: 'Morelos',
        level: 'municipal',
        active: false,
        scores: { sentencias: 19, fiscalizacion: 8, funcionarios: 10, deuda: 7, denuncias: 8, evasion: 8, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido el 30 de mayo 2026 por delincuencia organizada y extorsión.',
            fiscalizacion: 'Red de corrupción que operaba desde el ayuntamiento de Cuautla.',
            funcionarios: 'Detenido junto con tesorero (Jonathan Espinoza), oficial mayor (Pablo Portillo) y secretario municipal (Horacio).',
            deuda: 'Desvío de recursos públicos y esquema de extorsión.',
            denuncias: 'Denuncias de comerciantes, transportistas y familias extorsionadas.',
            evasion: 'PRÓFUGO inicialmente. Orden de aprehensión pendiente antes de captura.',
            nepotismo: 'Operadores administrativos como parte de la red criminal.',
        },
        timeline: [
            { year: '2025', event: 'Asume alcaldía de Cuautla' },
            { year: '2026', event: 'Orden de aprehensión. Prófugo brevemente. Detenido el 30 de mayo.' },
        ],
        sources: [
            { label: 'Infobae — Enjambre Morelos', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 206,
        name: 'Giovanni González Vieyra',
        role: 'Alcalde de Tlachichuca, Puebla',
        party: 'MORENA',
        state: 'Puebla',
        level: 'municipal',
        active: false,
        scores: { sentencias: 17, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 7, evasion: 3, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido el 7 de marzo 2025. Procesado por vínculos con organizaciones delictivas.',
            fiscalizacion: 'Bajo investigación federal.',
            funcionarios: 'Detenido junto con su hermano Uruviel (alcalde de Quimixtlán) y Ramiro (alcalde de San Nicolás Buenos Aires).',
            deuda: 'Red familiar controlando tres municipios señalada.',
            denuncias: 'Investigación federal por delincuencia organizada.',
            evasion: 'No evadió detención.',
            nepotismo: 'TRES HERMANOS como alcaldes simultáneos en Puebla. Red familiar de control municipal.',
        },
        timeline: [
            { year: '2025', event: 'Detenido junto con hermanos alcaldes en Operación Enjambre' },
        ],
        sources: [
            { label: 'Infobae — Hermanos González', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 207,
        name: 'Pedro Luis "Wicho"',
        role: 'Alcalde electo de Santo Tomás de los Plátanos, EdoMex',
        party: 'Sin dato',
        state: 'Estado de México',
        level: 'municipal',
        active: false,
        scores: { sentencias: 18, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 8, evasion: 9, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido en febrero 2025 en Valle de Bravo. Procesado por extorsión.',
            fiscalizacion: 'Uso de archivos municipales y padrones de programas sociales para intimidación.',
            funcionarios: 'Su esposa María del Rosario (expresidenta del mismo municipio) también detenida.',
            deuda: 'No documentado específicamente.',
            denuncias: 'Documentado por FGJEM.',
            evasion: 'HUYÓ el día de su toma de protesta cuando policías intentaron cumplir orden de aprehensión. Un grupo de personas agredió a los agentes. Capturado 2 meses después.',
            nepotismo: 'Matrimonio controlando la presidencia municipal en periodos consecutivos.',
        },
        timeline: [
            { year: '2024', event: 'Gana elección de Santo Tomás de los Plátanos' },
            { year: '2024', event: 'Huye el día de su toma de protesta al intentar ser detenido' },
            { year: '2025', event: 'Capturado en Valle de Bravo' },
        ],
        sources: [
            { label: 'SinEmbargo — Enjambre', url: 'https://www.sinembargo.mx' },
        ],
    },
    {
        id: 208,
        name: 'Ari Patrick Mendiola Mondragón',
        role: 'Exalcalde de Almoloya de Alquisiras, EdoMex',
        party: 'Sin dato',
        state: 'Estado de México',
        level: 'municipal',
        active: false,
        scores: { sentencias: 16, fiscalizacion: 7, funcionarios: 5, deuda: 6, denuncias: 7, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Vinculado a proceso por extorsión y acaparamiento de granos.',
            fiscalizacion: 'Aseguramiento de 100 toneladas de granos.',
            funcionarios: 'Investigación por red de extorsión municipal.',
            deuda: 'Acaparamiento de granos como mecanismo de control económico.',
            denuncias: 'Documentado por autoridades del EdoMex.',
            evasion: 'No evadió la justicia.',
            nepotismo: 'Control económico del municipio mediante acaparamiento.',
        },
        timeline: [
            { year: '2025', event: 'Detenido en Operación Enjambre. 100 toneladas de granos aseguradas.' },
        ],
        sources: [
            { label: 'Telediario — EdoMex', url: 'https://www.telediario.mx' },
        ],
    },
    // =====================================================
    // COACALCO — CASOS ORIGINALES
    // =====================================================
    {
        id: 1,
        name: 'David Sánchez Isidoro',
        role: 'Presidente Municipal de Coacalco (4 periodos)',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: true,
        scores: { sentencias: 22, fiscalizacion: 18, funcionarios: 14, deuda: 13, denuncias: 9, evasion: 9, nepotismo: 4 },
        breakdown: {
            sentencias: 'Condenado a 3 años 4 meses por desacato (2021). SCJN ordenó consignación penal en 2018. Proceso penal por concesión irregular del Deportivo Villa de las Flores.',
            fiscalizacion: 'OSFEM detectó 46 observaciones por $95.7M en ejercicio 2023. Obras sin comprobación, adjudicaciones indebidas, traspasos no autorizados.',
            funcionarios: 'Secretario particular (Alan Escalante) detenido por cohecho. Coordinador de Licencias detenido. Subdirector de Desarrollo Urbano detenido por extorsión.',
            deuda: 'Contrató $303M en deuda en 2013. Deuda total superó $1,000M. Endeudamiento >104%.',
            denuncias: 'Corrupción policiaca documentada. El Heraldo reportó corrupción generalizada (2025). Radar federal por Operación Enjambre.',
            evasion: 'Se amparó contra orden de detención de la SCJN. Desacató sentencia en más de 12 ocasiones. Ayuntamiento simuló amenazas de bomba para evadir embargos.',
            nepotismo: 'Concesionó Deportivo por 25 años. Contratos en Tesorería sin pasar por adquisiciones. Nómina especial con personal de despacho externo.',
        },
        timeline: [
            { year: '2009', event: 'Primer periodo como alcalde' },
            { year: '2013', event: 'Segundo periodo. Contrata $303M en deuda.' },
            { year: '2015', event: 'Concesiona Deportivo Villa de las Flores por 25 años' },
            { year: '2018', event: 'SCJN ordena consignación penal' },
            { year: '2021', event: 'Condenado a 3 años 4 meses. TEPJF revoca y restituye triunfo.' },
            { year: '2023', event: 'OSFEM detecta $95.7M en anomalías' },
            { year: '2025', event: 'Cuarto trienio. Radar federal Operación Enjambre.' },
        ],
        sources: [
            { label: 'SCJN — Consignación', url: 'https://www.proceso.com.mx/nacional/2018/1/16/la-corte-destituye-consigna-alcaldes-cabildos-del-edomex-de-puebla-198309.html' },
            { label: 'OSFEM — Auditoría 2023', url: 'https://www.osfem.gob.mx' },
            { label: 'TEPJF — Sentencia', url: 'https://www.te.gob.mx/front3/bulletins/detail/4393/0' },
            { label: 'Heraldo — Radar federal 2026', url: 'https://heraldodemexico.com.mx/opinion/2026/2/9/coacalco-en-el-radar-del-gobierno-federal-767261.html' },
        ],
    },
    {
        id: 2,
        name: 'Roberto Ruiz Moronatti',
        role: 'Expresidente Municipal de Coacalco / Exdiputado Federal',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: false,
        scores: { sentencias: 5, fiscalizacion: 16, funcionarios: 3, deuda: 15, denuncias: 6, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sin sentencias penales directas confirmadas.',
            fiscalizacion: 'OSFEM reportó pasivo de $640.7M. Endeudamiento 104.1%. Gastos financieros = 33% de ingresos.',
            funcionarios: 'No se documentaron detenciones directas.',
            deuda: 'Deuda per cápita: de $937 a $3,394. Tardarían 50 años en pagar.',
            denuncias: 'CONADE contradijo versión sobre devolución de $9.5M para estadio nunca construido.',
            evasion: 'Dejó alcaldía para buscar diputación federal con fuero.',
            nepotismo: 'No documentado con fuentes verificables.',
        },
        timeline: [
            { year: '2009', event: 'Asume presidencia municipal de Coacalco' },
            { year: '2012', event: 'Deja alcaldía. OSFEM reporta pasivo de $640.7M. Electo diputado federal.' },
        ],
        sources: [
            { label: 'OSFEM — Cuenta Pública 2012', url: 'https://www.osfem.gob.mx' },
        ],
    },
    {
        id: 3,
        name: 'Erwin Castelán Enríquez',
        role: 'Expresidente Municipal de Coacalco (2016-2018)',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: false,
        scores: { sentencias: 20, fiscalizacion: 12, funcionarios: 5, deuda: 10, denuncias: 6, evasion: 5, nepotismo: 2 },
        breakdown: {
            sentencias: 'SCJN ordenó destitución y consignación penal (enero 2018). Pena de 5-10 años.',
            fiscalizacion: 'Heredó y no resolvió deuda >$800M en laudos.',
            funcionarios: 'Cabildo completo destituido por la SCJN.',
            deuda: 'Laudos laborales y administrativos por >$800M sin resolver.',
            denuncias: 'Empresarios denunciaron maniobras para evadir embargos (amenazas de bomba simuladas).',
            evasion: 'Desacató sentencia de amparo reiteradamente.',
            nepotismo: 'No documentado.',
        },
        timeline: [
            { year: '2016', event: 'Asume presidencia municipal' },
            { year: '2018', event: 'SCJN destituye cabildo completo y ordena consignación' },
        ],
        sources: [
            { label: 'Proceso — SCJN', url: 'https://www.proceso.com.mx/nacional/2018/1/16/la-corte-destituye-consigna-alcaldes-cabildos-del-edomex-de-puebla-198309.html' },
            { label: 'El Universal — Adeudos', url: 'https://www.eluniversal.com.mx/metropoli/edomex/empresarios-acusan-adeudo-de-coacalco/' },
        ],
    },
];
