// =====================================================
// CORRUPTÓMETRO MX — BASE DE DATOS NACIONAL
// Fuentes: OSFEM, SCJN, TEPJF, ASF, SESNSP, SHCP,
// Proceso, El Universal, Infobae, La Jornada, Milenio
// Última actualización: Julio 2026
// =====================================================

const SCORING_CRITERIA = [
    { id: 'sentencias', label: 'Sentencias o procesos penales', maxPoints: 25, desc: 'Condenas, consignaciones o procesos penales activos' },
    { id: 'fiscalizacion', label: 'Observaciones de fiscalización', maxPoints: 20, desc: 'Hallazgos de OSFEM, ASF o auditorías con montos no comprobados' },
    { id: 'funcionarios', label: 'Funcionarios detenidos / red', maxPoints: 15, desc: 'Colaboradores directos detenidos o red criminal documentada' },
    { id: 'deuda', label: 'Deuda / daño patrimonial', maxPoints: 15, desc: 'Desvío de recursos, peculado o daño al erario documentado' },
    { id: 'denuncias', label: 'Denuncias documentadas', maxPoints: 10, desc: 'Denuncias ciudadanas, periodísticas o de organismos verificadas' },
    { id: 'evasion', label: 'Evasión de justicia / desacato', maxPoints: 10, desc: 'Amparos para evadir detención, fuga, desacato judicial' },
    { id: 'nepotismo', label: 'Nepotismo / conflicto de interés', maxPoints: 5, desc: 'Concesiones irregulares, familiares en nómina, contratos dirigidos' },
];

const officials = [
    // =====================================================
    // EXGOBERNADORES — NIVEL ESTATAL / FEDERAL
    // =====================================================
    {
        id: 101,
        name: 'Javier Duarte de Ochoa',
        role: 'Exgobernador de Veracruz (2010-2016)',
        party: 'PRI',
        state: 'Veracruz',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 25, fiscalizacion: 20, funcionarios: 14, deuda: 15, denuncias: 10, evasion: 10, nepotismo: 4 },
        breakdown: {
            sentencias: 'Sentenciado a 9 años por asociación delictuosa y lavado de dinero. Vinculado a nuevo proceso en 2026 por desvío de $5M. Detenido en Guatemala en 2017.',
            fiscalizacion: 'ASF documentó desvíos masivos del erario veracruzano. Desaparición de recursos del sistema de salud estatal.',
            funcionarios: 'Múltiples excolaboradores detenidos y procesados. Red de corrupción sistémica en el gobierno estatal.',
            deuda: 'Daño al erario estimado en miles de millones. Desvío de recursos de programas de salud, educación e infraestructura.',
            denuncias: 'Caso ampliamente documentado por medios nacionales e internacionales. Denuncias de familiares de desaparecidos.',
            evasion: 'Prófugo durante 6 meses. Capturado en Guatemala. Jueza negó libertad anticipada en noviembre 2025 pese a cumplir 95% de condena.',
            nepotismo: 'Empresas fantasma vinculadas a su círculo. Propiedades a nombre de prestanombres.',
        },
        timeline: [
            { year: '2010', event: 'Asume gubernatura de Veracruz' },
            { year: '2016', event: 'Solicita licencia 20 días antes de terminar mandato. Se fuga.' },
            { year: '2017', event: 'Capturado en Guatemala. Extraditado a México.' },
            { year: '2018', event: 'Sentenciado a 9 años de prisión' },
            { year: '2025', event: 'Jueza niega libertad anticipada' },
            { year: '2026', event: 'Vinculado a nuevo proceso por desvío adicional' },
        ],
        sources: [
            { label: 'Proceso — Captura', url: 'https://www.proceso.com.mx' },
            { label: 'Infobae — Sentencia', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 102,
        name: 'César Duarte Jáquez',
        role: 'Exgobernador de Chihuahua (2010-2016)',
        party: 'PRI',
        state: 'Chihuahua',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 23, fiscalizacion: 20, funcionarios: 13, deuda: 15, denuncias: 9, evasion: 8, nepotismo: 4 },
        breakdown: {
            sentencias: 'Preso en el Altiplano. Acusado de lavado de dinero por más de $73M. Ficha roja de Interpol.',
            fiscalizacion: 'Red de corrupción que generó daños al erario por $6,000M según autoridades de Chihuahua.',
            funcionarios: 'Entre 50 y 80 amparos tramitados por excolaboradores para evitar detención.',
            deuda: 'Desvío estimado en $6,000 millones de pesos del erario chihuahuense.',
            denuncias: 'Documentado extensamente. Múltiples denuncias de la administración sucesora.',
            evasion: 'Prófugo con ficha roja de Interpol. Detenido en EE.UU. y extraditado.',
            nepotismo: 'Red de prestanombres y empresas fantasma documentada.',
        },
        timeline: [
            { year: '2010', event: 'Asume gubernatura de Chihuahua' },
            { year: '2016', event: 'Termina mandato. Huye del país.' },
            { year: '2020', event: 'Detenido en Estados Unidos' },
            { year: '2023', event: 'Extraditado a México. Internado en penal del Altiplano.' },
        ],
        sources: [
            { label: 'Reforma — Detención', url: 'https://www.reforma.com' },
            { label: 'El Universal — Proceso', url: 'https://www.eluniversal.com.mx' },
        ],
    },
    {
        id: 103,
        name: 'Roberto Borge Angulo',
        role: 'Exgobernador de Quintana Roo (2011-2016)',
        party: 'PRI',
        state: 'Quintana Roo',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 21, fiscalizacion: 17, funcionarios: 10, deuda: 13, denuncias: 8, evasion: 8, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido en Panamá en 2017. Procesado por lavado de dinero y delincuencia organizada. Absuelto de delincuencia organizada en 2026; continúa proceso bajo prisión domiciliaria.',
            fiscalizacion: 'Venta irregular de terrenos públicos de Quintana Roo a precios por debajo del mercado.',
            funcionarios: 'Red de funcionarios involucrados en operaciones inmobiliarias irregulares.',
            deuda: 'Daño patrimonial por venta de predios estatales. Operaciones con recursos de procedencia ilícita.',
            denuncias: 'Denunciado por la administración sucesora y organizaciones ciudadanas.',
            evasion: 'Prófugo. Capturado en Panamá y deportado a México.',
            nepotismo: 'Benefició a allegados con ventas de terrenos públicos a precios preferenciales.',
        },
        timeline: [
            { year: '2011', event: 'Asume gubernatura de Quintana Roo' },
            { year: '2017', event: 'Detenido en Panamá. Deportado a México.' },
            { year: '2026', event: 'Absuelto de delincuencia organizada. Prisión domiciliaria con brazalete.' },
        ],
        sources: [
            { label: 'La Verdad Noticias', url: 'https://laverdadnoticias.com' },
        ],
    },
    {
        id: 104,
        name: 'Tomás Yarrington Ruvalcaba',
        role: 'Exgobernador de Tamaulipas (1999-2005)',
        party: 'PRI',
        state: 'Tamaulipas',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 24, fiscalizacion: 15, funcionarios: 12, deuda: 14, denuncias: 10, evasion: 9, nepotismo: 3 },
        breakdown: {
            sentencias: 'Procesado en EE.UU. por lavado de dinero y vínculos con narcotráfico. Orden de aprehensión desde 2012.',
            fiscalizacion: 'Acusaciones de recibir sobornos del crimen organizado durante su mandato.',
            funcionarios: 'Investigaciones contra red de exfuncionarios tamaulipecos.',
            deuda: 'Lavado de dinero por millones de dólares a través de propiedades en Texas.',
            denuncias: 'Caso documentado por la DEA y autoridades de EE.UU.',
            evasion: 'Prófugo durante años. Detenido en Italia en 2017.',
            nepotismo: 'Propiedades en EE.UU. a nombre de prestanombres.',
        },
        timeline: [
            { year: '1999', event: 'Asume gubernatura de Tamaulipas' },
            { year: '2012', event: 'Orden de aprehensión emitida' },
            { year: '2017', event: 'Detenido en Italia' },
        ],
        sources: [
            { label: 'Proceso — Detención', url: 'https://www.proceso.com.mx' },
        ],
    },
    {
        id: 105,
        name: 'Eugenio Hernández Flores',
        role: 'Exgobernador de Tamaulipas (2005-2010)',
        party: 'PRI',
        state: 'Tamaulipas',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 22, fiscalizacion: 14, funcionarios: 10, deuda: 13, denuncias: 8, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido en 2017. Procesado por lavado de dinero y vínculos con narcotráfico.',
            fiscalizacion: 'Señalamientos de desvío de recursos durante su administración.',
            funcionarios: 'Exfuncionarios investigados por vínculos con el crimen organizado.',
            deuda: 'Recursos de procedencia ilícita canalizados a través de empresas.',
            denuncias: 'Investigaciones de la PGR y DEA.',
            evasion: 'Mantuvo perfil bajo antes de su detención.',
            nepotismo: 'Red de prestanombres documentada.',
        },
        timeline: [
            { year: '2005', event: 'Asume gubernatura de Tamaulipas' },
            { year: '2017', event: 'Detenido por autoridades federales' },
        ],
        sources: [
            { label: 'Milenio — Detención', url: 'https://www.milenio.com' },
        ],
    },
    {
        id: 106,
        name: 'Roberto Sandoval Castañeda',
        role: 'Exgobernador de Nayarit (2011-2017)',
        party: 'PRI',
        state: 'Nayarit',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 23, fiscalizacion: 18, funcionarios: 11, deuda: 14, denuncias: 9, evasion: 5, nepotismo: 4 },
        breakdown: {
            sentencias: 'Sentenciado por falsificación de documentos. Preso en CEFERESO No. 4 desde 2021. Enfrenta cargos adicionales por lavado de dinero, enriquecimiento ilícito y asociación delictuosa.',
            fiscalizacion: 'Juicio político aprobado por desvío de $2,700M del erario nayarita.',
            funcionarios: 'Red de funcionarios involucrados en desvíos documentada.',
            deuda: 'Desvío estimado en $2,700 millones de pesos. Enriquecimiento ilícito.',
            denuncias: 'Ciudadanos documentaron en expedientes: desvío de recursos, violaciones a la Constitución estatal.',
            evasion: 'No logró evadir la justicia efectivamente.',
            nepotismo: 'Propiedades irregulares, incluida una en San Blas obtenida con documentos falsificados.',
        },
        timeline: [
            { year: '2011', event: 'Asume gubernatura de Nayarit' },
            { year: '2018', event: 'Congreso aprueba juicio político por desvío de $2,700M' },
            { year: '2021', event: 'Preso en CEFERESO No. 4' },
            { year: '2025', event: 'Sentenciado por falsificación de documentos' },
        ],
        sources: [
            { label: 'El Informador — Sentencia', url: 'https://www.informador.mx' },
        ],
    },
    {
        id: 107,
        name: 'Mario Marín Torres',
        role: 'Exgobernador de Puebla (2005-2011)',
        party: 'PRI',
        state: 'Puebla',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 22, fiscalizacion: 10, funcionarios: 8, deuda: 8, denuncias: 10, evasion: 6, nepotismo: 3 },
        breakdown: {
            sentencias: 'Preso. Regresó al penal del Altiplano en abril 2025 tras revocación de prisión domiciliaria. Procesado por tortura contra la periodista Lydia Cacho.',
            fiscalizacion: 'Señalamientos de uso irregular de recursos públicos.',
            funcionarios: 'Caso vinculado a red de protección a Kamel Nacif (empresario).',
            deuda: 'Uso de aparato estatal para perseguir periodistas y proteger intereses privados.',
            denuncias: 'Caso Lydia Cacho ampliamente documentado nacional e internacionalmente. Grabaciones telefónicas lo implican directamente.',
            evasion: 'Prófugo antes de ser detenido. Gozó de prisión domiciliaria hasta su revocación.',
            nepotismo: 'Relación documentada con empresario Kamel Nacif para protección mutua.',
        },
        timeline: [
            { year: '2005', event: 'Asume gubernatura de Puebla' },
            { year: '2005', event: 'Caso Lydia Cacho: grabaciones lo implican en tortura a periodista' },
            { year: '2021', event: 'Detenido tras años de investigación' },
            { year: '2025', event: 'Regresa al penal del Altiplano tras revocación de prisión domiciliaria' },
        ],
        sources: [
            { label: 'La Verdad Noticias', url: 'https://laverdadnoticias.com' },
        ],
    },
    {
        id: 108,
        name: 'Jaime Rodríguez Calderón "El Bronco"',
        role: 'Exgobernador de Nuevo León (2015-2021)',
        party: 'Independiente',
        state: 'Nuevo León',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 20, fiscalizacion: 14, funcionarios: 6, deuda: 10, denuncias: 8, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Preso en CERESO de Apodaca. Acusado de desvío de recursos públicos y lavado de dinero durante campaña presidencial 2018.',
            fiscalizacion: 'Investigado por uso de recursos públicos para financiar campaña presidencial.',
            funcionarios: 'Excolaboradores investigados por participación en irregularidades de campaña.',
            deuda: 'Desvío de recursos públicos estatales para fines electorales.',
            denuncias: 'Documentado por medios y autoridades electorales.',
            evasion: 'No evadió efectivamente la justicia.',
            nepotismo: 'Uso de estructura gubernamental para fines personales.',
        },
        timeline: [
            { year: '2015', event: 'Gana gubernatura como candidato independiente' },
            { year: '2018', event: 'Se postula a la presidencia. Irregularidades en campaña.' },
            { year: '2022', event: 'Detenido e ingresado a CERESO de Apodaca' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 109,
        name: 'Andrés Granier Melo',
        role: 'Exgobernador de Tabasco (2007-2012)',
        party: 'PRI',
        state: 'Tabasco',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 17, funcionarios: 7, deuda: 14, denuncias: 8, evasion: 4, nepotismo: 4 },
        breakdown: {
            sentencias: 'Condenado a 10 años 10 meses por peculado. Sentencia revocada en 2019 tras 5 años y medio preso. Liberado.',
            fiscalizacion: 'Desvío de $196.9M del Seguro Popular documentado por auditorías.',
            funcionarios: 'Funcionarios de salud involucrados en desvío del Seguro Popular.',
            deuda: 'Peculado por $196.9 millones de pesos del programa Seguro Popular.',
            denuncias: 'Caso mediático: pijamas italianas, lujos en prisión documentados por medios.',
            evasion: 'No evadió la justicia pero gozó de privilegios en prisión.',
            nepotismo: 'Estilo de vida ostentoso incompatible con salario público.',
        },
        timeline: [
            { year: '2007', event: 'Asume gubernatura de Tabasco' },
            { year: '2013', event: 'Detenido por peculado' },
            { year: '2019', event: 'Sentencia revocada. Liberado tras 5.5 años preso.' },
        ],
        sources: [
            { label: 'Infobae — Caso', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 110,
        name: 'Rodrigo Medina de la Cruz',
        role: 'Exgobernador de Nuevo León (2009-2015)',
        party: 'PRI',
        state: 'Nuevo León',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 14, fiscalizacion: 14, funcionarios: 5, deuda: 11, denuncias: 7, evasion: 5, nepotismo: 3 },
        breakdown: {
            sentencias: 'Vinculado a proceso por ejercicio indebido de funciones públicas. Enfrentó proceso en libertad. Exonerado en 2018.',
            fiscalizacion: 'Presuntas irregularidades en incentivos a la armadora KIA Motors.',
            funcionarios: 'Investigaciones contra exfuncionarios de su administración.',
            deuda: 'Peculado y daño patrimonial señalados. Preso en Topo Chico brevemente.',
            denuncias: 'Caso KIA Motors documentado por medios nacionales.',
            evasion: 'Amparos utilizados para enfrentar proceso en libertad.',
            nepotismo: 'Incentivos fiscales cuestionados a empresa automotriz.',
        },
        timeline: [
            { year: '2009', event: 'Asume gubernatura de Nuevo León' },
            { year: '2016', event: 'Vinculado a proceso por caso KIA' },
            { year: '2018', event: 'Exonerado tras proceso' },
        ],
        sources: [
            { label: 'Alcaldes de México', url: 'https://www.alcaldesdemexico.com' },
        ],
    },
    {
        id: 111,
        name: 'Mario Villanueva Madrid',
        role: 'Exgobernador de Quintana Roo (1993-1999)',
        party: 'PRI',
        state: 'Quintana Roo',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 25, fiscalizacion: 12, funcionarios: 8, deuda: 12, denuncias: 9, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sentenciado en 2020 por delitos contra la salud. 19 años en prisión. Actualmente en arresto domiciliario desde 2020 por edad y condiciones médicas.',
            fiscalizacion: 'Procesado por vínculos con narcotráfico durante su mandato.',
            funcionarios: 'Colaboradores involucrados en red de protección al narcotráfico.',
            deuda: 'Recursos de procedencia ilícita por protección a cárteles.',
            denuncias: 'Investigado por autoridades mexicanas y estadounidenses.',
            evasion: 'Prófugo antes de su captura. 19 años preso.',
            nepotismo: 'Red de protección al crimen organizado desde la gubernatura.',
        },
        timeline: [
            { year: '1993', event: 'Asume gubernatura de Quintana Roo' },
            { year: '2001', event: 'Detenido' },
            { year: '2020', event: 'Arresto domiciliario tras 19 años preso' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 112,
        name: 'Rubén Rocha Moya',
        role: 'Gobernador de Sinaloa (2021-presente)',
        party: 'MORENA',
        state: 'Sinaloa',
        level: 'estatal',
        active: true, status: 'en_funciones',
        scores: { sentencias: 10, fiscalizacion: 8, funcionarios: 5, deuda: 5, denuncias: 10, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Acusado por EE.UU. de vínculos con narcotráfico. FGR inició investigación. Sin sentencia ni orden de aprehensión hasta la fecha.',
            fiscalizacion: 'Bajo investigación. Sin hallazgos formales publicados aún.',
            funcionarios: 'Crisis de seguridad en Sinaloa con enfrentamientos entre facciones del Cártel de Sinaloa.',
            deuda: 'Sin documentación de daño patrimonial directo hasta ahora.',
            denuncias: 'Acusación de EE.UU. con alto impacto mediático. Investigación de FGR abierta.',
            evasion: 'Defiende su inocencia. No ha evadido proceso.',
            nepotismo: 'Señalamientos de cercanía con figuras del crimen organizado.',
        },
        timeline: [
            { year: '2021', event: 'Asume gubernatura de Sinaloa' },
            { year: '2024', event: 'Crisis de seguridad en Culiacán tras captura de Zambada' },
            { year: '2026', event: 'EE.UU. lo acusa de vínculos con narcotráfico. FGR investiga.' },
        ],
        sources: [
            { label: 'El Siglo de Torreón', url: 'https://www.elsiglodetorreon.com.mx' },
        ],
    },
    {
        id: 113,
        name: 'Ricardo Gallardo Cardona',
        role: 'Gobernador de San Luis Potosí (2021-presente)',
        party: 'PVEM',
        state: 'San Luis Potosí',
        level: 'estatal',
        active: true, status: 'en_funciones',
        scores: { sentencias: 12, fiscalizacion: 10, funcionarios: 5, deuda: 6, denuncias: 8, evasion: 4, nepotismo: 4 },
        breakdown: {
            sentencias: 'Estuvo preso en 2015. Antecedentes penales previos a la gubernatura. Bajo escrutinio por presuntas irregularidades.',
            fiscalizacion: 'Señalamientos de manejo opaco de recursos estatales.',
            funcionarios: 'Investigaciones contra miembros de su administración.',
            deuda: 'Cuestionamientos sobre licitaciones y contratos.',
            denuncias: 'Medios nacionales y organizaciones civiles han documentado señalamientos.',
            evasion: 'Antecedentes penales pero logró postularse y ganar gubernatura.',
            nepotismo: 'Señalamientos de concentración de poder y contratos dirigidos.',
        },
        timeline: [
            { year: '2015', event: 'Estuvo preso por cargos penales' },
            { year: '2021', event: 'Gana gubernatura por el PVEM' },
        ],
        sources: [
            { label: 'Polls MX — Análisis', url: 'https://polls.politico.mx' },
        ],
    },
    {
        id: 114,
        name: 'Luis Armando Reynoso Femat',
        role: 'Exgobernador de Aguascalientes (2004-2010)',
        party: 'PAN',
        state: 'Aguascalientes',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 16, fiscalizacion: 14, funcionarios: 4, deuda: 9, denuncias: 6, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Declarado culpable de ejercicio indebido del servicio público y peculado por $13.8M. Sentenciado a 2 años 9 meses (pagó pena en libertad por ser menor a 5 años).',
            fiscalizacion: 'Fingió adquisición de tomógrafo computarizado para el Instituto de Salud estatal.',
            funcionarios: 'Funcionarios de salud involucrados en compra ficticia.',
            deuda: 'Peculado por $13.8M del erario de Aguascalientes.',
            denuncias: 'Documentado por medios y autoridades judiciales.',
            evasion: 'Amparos para enfrentar proceso. Pena pagada en libertad.',
            nepotismo: 'Adquisición ficticia de equipo médico.',
        },
        timeline: [
            { year: '2004', event: 'Asume gubernatura de Aguascalientes' },
            { year: '2019', event: 'Declarado culpable por peculado y ejercicio indebido' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 115,
        name: 'Flavino Ríos Alvarado',
        role: 'Exgobernador interino de Veracruz (2016)',
        party: 'PRI',
        state: 'Veracruz',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 8, funcionarios: 4, deuda: 6, denuncias: 7, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Procesado por encubrimiento. Facilitó la fuga de Javier Duarte al concederle licencia como gobernador.',
            fiscalizacion: 'Señalado por facilitar la impunidad de su antecesor.',
            funcionarios: 'Complicidad documentada con la red de Duarte.',
            deuda: 'Complicidad en encubrimiento, no desvío directo documentado.',
            denuncias: 'Medios documentaron su papel en facilitar la fuga de Duarte.',
            evasion: 'Enfrentó proceso judicial.',
            nepotismo: 'Lealtad política sobre legalidad al facilitar licencia de Duarte.',
        },
        timeline: [
            { year: '2016', event: 'Asume interinato de Veracruz. Facilita licencia a Duarte.' },
            { year: '2017', event: 'Procesado por encubrimiento' },
        ],
        sources: [
            { label: 'Alcaldes de México', url: 'https://www.alcaldesdemexico.com' },
        ],
    },
    {
        id: 116,
        name: 'Jorge Torres López',
        role: 'Exgobernador interino de Coahuila (2011)',
        party: 'PRI',
        state: 'Coahuila',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 20, fiscalizacion: 14, funcionarios: 6, deuda: 12, denuncias: 8, evasion: 10, nepotismo: 3 },
        breakdown: {
            sentencias: 'Acusado por la DEA de conspiración para lavado de dinero. En la lista de "fugitivos más buscados" desde 2016.',
            fiscalizacion: 'Depositó fondos saqueados del erario de Coahuila en paraísos fiscales y bancos de Texas.',
            funcionarios: 'Red vinculada al exgobernador Humberto Moreira.',
            deuda: 'Saqueo del erario coahuilense canalizado a cuentas en el extranjero.',
            denuncias: 'Investigaciones de la DEA y autoridades de EE.UU.',
            evasion: 'PRÓFUGO. En lista de fugitivos más buscados de la DEA desde 2016.',
            nepotismo: 'Red de lavado de dinero transnacional.',
        },
        timeline: [
            { year: '2011', event: 'Gobernador interino de Coahuila en sustitución de Moreira' },
            { year: '2016', event: 'DEA lo declara fugitivo. Paradero desconocido.' },
        ],
        sources: [
            { label: 'Proceso — DEA', url: 'https://www.proceso.com.mx' },
        ],
    },
    // =====================================================
    // OPERACIÓN ENJAMBRE — MUNICIPALES
    // =====================================================
    {
        id: 201,
        name: 'María Elena Martínez Robles',
        role: 'Expresidenta Municipal de Amanalco, EdoMex',
        party: 'MC/MORENA',
        state: 'Estado de México',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 25, fiscalizacion: 8, funcionarios: 10, deuda: 5, denuncias: 9, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sentenciada a 70 AÑOS de prisión por homicidio calificado. Ordenó asesinato del síndico municipal y su chofer en enero 2023.',
            fiscalizacion: 'Señalamientos de uso irregular de recursos municipales.',
            funcionarios: 'Coordinó con integrantes de La Familia Michoacana para mantener control político.',
            deuda: 'No documentado específicamente.',
            denuncias: 'Caso documentado por FGJEM. Operación Enjambre.',
            evasion: 'Detenida en noviembre 2024.',
            nepotismo: 'Control político absoluto del municipio mediante intimidación.',
        },
        timeline: [
            { year: '2022', event: 'Asume presidencia municipal. Se afilia a Morena.' },
            { year: '2023', event: 'Ordena asesinato del síndico municipal y chofer' },
            { year: '2024', event: 'Detenida en Operación Enjambre' },
            { year: '2025', event: 'Sentenciada a 70 años de prisión' },
        ],
        sources: [
            { label: 'El Financiero — Enjambre', url: 'https://www.elfinanciero.com.mx' },
            { label: 'Telediario — Sentencia', url: 'https://www.telediario.mx' },
        ],
    },
    {
        id: 202,
        name: 'Diego Rivera Navarro',
        role: 'Presidente Municipal de Tequila, Jalisco',
        party: 'MC',
        state: 'Jalisco',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 22, fiscalizacion: 12, funcionarios: 14, deuda: 8, denuncias: 9, evasion: 3, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido el 5 de febrero 2026. Prisión preventiva oficiosa en Almoloya de Juárez por extorsión y vínculos con CJNG.',
            fiscalizacion: 'Esquema de extorsión sistemática desde oficinas gubernamentales.',
            funcionarios: 'Detenido junto con director de Padrón y Licencias, Tesorería, Catastro y Obras Públicas. Todos vinculados a esquema de extorsión para el CJNG.',
            deuda: 'Recursos obtenidos mediante extorsión entregados al CJNG a través de intermediario "El Rey Mago".',
            denuncias: 'Denuncias de empresarios cerveceros y tequileros extorsionados.',
            evasion: 'No logró evadir detención.',
            nepotismo: 'Funcionarios de primer círculo como operadores del esquema criminal.',
        },
        timeline: [
            { year: '2024', event: 'Secuestro de candidatos opositores durante campaña electoral' },
            { year: '2025', event: 'Asume presidencia municipal de Tequila' },
            { year: '2026', event: 'Detenido en Operación Enjambre junto con 4 funcionarios' },
        ],
        sources: [
            { label: 'Infobae — Enjambre Jalisco', url: 'https://www.infobae.com' },
            { label: 'SinEmbargo — Detención', url: 'https://www.sinembargo.mx' },
        ],
    },
    {
        id: 203,
        name: 'Agustín Toledano Amaro',
        role: 'Presidente Municipal de Atlatlahucan, Morelos',
        party: 'PAN',
        state: 'Morelos',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 8, funcionarios: 8, deuda: 6, denuncias: 9, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido el 20 de mayo 2026 por presuntos delitos de extorsión y delincuencia organizada.',
            fiscalizacion: 'Investigación por desvío de recursos municipales hacia red criminal.',
            funcionarios: 'Aparece en video con presuntos integrantes del crimen organizado.',
            deuda: 'Financiamiento irregular de campañas electorales señalado.',
            denuncias: 'Denuncias ciudadanas por extorsión. Video lo vincula con criminales.',
            evasion: 'Promovió amparo contra orden de aprehensión (desechado parcialmente).',
            nepotismo: 'Vínculos con exgobernador Marco Adame Castillo.',
        },
        timeline: [
            { year: '2025', event: 'Asume presidencia municipal por coalición PAN-PRI-PRD' },
            { year: '2025', event: 'Aparece en video con presuntos criminales' },
            { year: '2026', event: 'Detenido en Operación Enjambre' },
        ],
        sources: [
            { label: 'Expansión — Morelos', url: 'https://politica.expansion.mx' },
        ],
    },
    {
        id: 204,
        name: 'Irving Sánchez Zavala',
        role: 'Exalcalde de Yecapixtla, Morelos',
        party: 'MORENA',
        state: 'Morelos',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 17, fiscalizacion: 7, funcionarios: 6, deuda: 6, denuncias: 8, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido en mayo 2026. Acusado de formar parte de estructura política que permitió financiamiento criminal de campañas.',
            fiscalizacion: 'Investigación por vínculos con red de corrupción.',
            funcionarios: 'Parte de red de funcionarios detenidos en Morelos.',
            deuda: 'Presunto financiamiento de campaña por el crimen organizado.',
            denuncias: 'FGR reveló vínculos con homicidio de expresidentes municipales y financiamiento criminal.',
            evasion: 'No evadió la justicia.',
            nepotismo: 'Red política-criminal en la región.',
        },
        timeline: [
            { year: '2026', event: 'Detenido en Operación Enjambre en Morelos' },
        ],
        sources: [
            { label: 'Expansión — Detención', url: 'https://politica.expansion.mx' },
        ],
    },
    {
        id: 205,
        name: 'Jesús Corona Damián',
        role: 'Alcalde de Cuautla, Morelos',
        party: 'MORENA',
        state: 'Morelos',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 19, fiscalizacion: 8, funcionarios: 10, deuda: 7, denuncias: 8, evasion: 8, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido el 30 de mayo 2026 por delincuencia organizada y extorsión.',
            fiscalizacion: 'Red de corrupción que operaba desde el ayuntamiento de Cuautla.',
            funcionarios: 'Detenido junto con tesorero (Jonathan Espinoza), oficial mayor (Pablo Portillo) y secretario municipal (Horacio).',
            deuda: 'Desvío de recursos públicos y esquema de extorsión.',
            denuncias: 'Denuncias de comerciantes, transportistas y familias extorsionadas.',
            evasion: 'PRÓFUGO inicialmente. Orden de aprehensión pendiente antes de captura.',
            nepotismo: 'Operadores administrativos como parte de la red criminal.',
        },
        timeline: [
            { year: '2025', event: 'Asume alcaldía de Cuautla' },
            { year: '2026', event: 'Orden de aprehensión. Prófugo brevemente. Detenido el 30 de mayo.' },
        ],
        sources: [
            { label: 'Infobae — Enjambre Morelos', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 206,
        name: 'Giovanni González Vieyra',
        role: 'Alcalde de Tlachichuca, Puebla',
        party: 'MORENA',
        state: 'Puebla',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 17, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 7, evasion: 3, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido el 7 de marzo 2025. Procesado por vínculos con organizaciones delictivas.',
            fiscalizacion: 'Bajo investigación federal.',
            funcionarios: 'Detenido junto con su hermano Uruviel (alcalde de Quimixtlán) y Ramiro (alcalde de San Nicolás Buenos Aires).',
            deuda: 'Red familiar controlando tres municipios señalada.',
            denuncias: 'Investigación federal por delincuencia organizada.',
            evasion: 'No evadió detención.',
            nepotismo: 'TRES HERMANOS como alcaldes simultáneos en Puebla. Red familiar de control municipal.',
        },
        timeline: [
            { year: '2025', event: 'Detenido junto con hermanos alcaldes en Operación Enjambre' },
        ],
        sources: [
            { label: 'Infobae — Hermanos González', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 207,
        name: 'Pedro Luis "Wicho"',
        role: 'Alcalde electo de Santo Tomás de los Plátanos, EdoMex',
        party: 'Sin dato',
        state: 'Estado de México',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 8, evasion: 9, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido en febrero 2025 en Valle de Bravo. Procesado por extorsión.',
            fiscalizacion: 'Uso de archivos municipales y padrones de programas sociales para intimidación.',
            funcionarios: 'Su esposa María del Rosario (expresidenta del mismo municipio) también detenida.',
            deuda: 'No documentado específicamente.',
            denuncias: 'Documentado por FGJEM.',
            evasion: 'HUYÓ el día de su toma de protesta cuando policías intentaron cumplir orden de aprehensión. Un grupo de personas agredió a los agentes. Capturado 2 meses después.',
            nepotismo: 'Matrimonio controlando la presidencia municipal en periodos consecutivos.',
        },
        timeline: [
            { year: '2024', event: 'Gana elección de Santo Tomás de los Plátanos' },
            { year: '2024', event: 'Huye el día de su toma de protesta al intentar ser detenido' },
            { year: '2025', event: 'Capturado en Valle de Bravo' },
        ],
        sources: [
            { label: 'SinEmbargo — Enjambre', url: 'https://www.sinembargo.mx' },
        ],
    },
    {
        id: 208,
        name: 'Ari Patrick Mendiola Mondragón',
        role: 'Exalcalde de Almoloya de Alquisiras, EdoMex',
        party: 'Sin dato',
        state: 'Estado de México',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 16, fiscalizacion: 7, funcionarios: 5, deuda: 6, denuncias: 7, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Vinculado a proceso por extorsión y acaparamiento de granos.',
            fiscalizacion: 'Aseguramiento de 100 toneladas de granos.',
            funcionarios: 'Investigación por red de extorsión municipal.',
            deuda: 'Acaparamiento de granos como mecanismo de control económico.',
            denuncias: 'Documentado por autoridades del EdoMex.',
            evasion: 'No evadió la justicia.',
            nepotismo: 'Control económico del municipio mediante acaparamiento.',
        },
        timeline: [
            { year: '2025', event: 'Detenido en Operación Enjambre. 100 toneladas de granos aseguradas.' },
        ],
        sources: [
            { label: 'Telediario — EdoMex', url: 'https://www.telediario.mx' },
        ],
    },
    // =====================================================
    // COACALCO — CASOS ORIGINALES
    // =====================================================
    {
        id: 1,
        name: 'David Sánchez Isidoro',
        role: 'Presidente Municipal de Coacalco (4 periodos)',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: true, status: 'en_funciones',
        scores: { sentencias: 22, fiscalizacion: 18, funcionarios: 14, deuda: 13, denuncias: 9, evasion: 9, nepotismo: 4 },
        breakdown: {
            sentencias: 'Condenado a 3 años 4 meses por desacato (2021). SCJN ordenó consignación penal en 2018. Proceso penal por concesión irregular del Deportivo Villa de las Flores.',
            fiscalizacion: 'OSFEM detectó 46 observaciones por $95.7M en ejercicio 2023. Obras sin comprobación, adjudicaciones indebidas, traspasos no autorizados.',
            funcionarios: 'Secretario particular (Alan Escalante) detenido por cohecho. Coordinador de Licencias detenido. Subdirector de Desarrollo Urbano detenido por extorsión.',
            deuda: 'Contrató $303M en deuda en 2013. Deuda total superó $1,000M. Endeudamiento >104%.',
            denuncias: 'Corrupción policiaca documentada. El Heraldo reportó corrupción generalizada (2025). Radar federal por Operación Enjambre.',
            evasion: 'Se amparó contra orden de detención de la SCJN. Desacató sentencia en más de 12 ocasiones. Ayuntamiento simuló amenazas de bomba para evadir embargos.',
            nepotismo: 'Concesionó Deportivo por 25 años. Contratos en Tesorería sin pasar por adquisiciones. Nómina especial con personal de despacho externo.',
        },
        timeline: [
            { year: '2009', event: 'Primer periodo como alcalde' },
            { year: '2013', event: 'Segundo periodo. Contrata $303M en deuda.' },
            { year: '2015', event: 'Concesiona Deportivo Villa de las Flores por 25 años' },
            { year: '2018', event: 'SCJN ordena consignación penal' },
            { year: '2021', event: 'Condenado a 3 años 4 meses. TEPJF revoca y restituye triunfo.' },
            { year: '2023', event: 'OSFEM detecta $95.7M en anomalías' },
            { year: '2025', event: 'Cuarto trienio. Radar federal Operación Enjambre.' },
        ],
        sources: [
            { label: 'SCJN — Consignación', url: 'https://www.proceso.com.mx/nacional/2018/1/16/la-corte-destituye-consigna-alcaldes-cabildos-del-edomex-de-puebla-198309.html' },
            { label: 'OSFEM — Auditoría 2023', url: 'https://www.osfem.gob.mx' },
            { label: 'TEPJF — Sentencia', url: 'https://www.te.gob.mx/front3/bulletins/detail/4393/0' },
            { label: 'Heraldo — Radar federal 2026', url: 'https://heraldodemexico.com.mx/opinion/2026/2/9/coacalco-en-el-radar-del-gobierno-federal-767261.html' },
        ],
    },
    {
        id: 2,
        name: 'Roberto Ruiz Moronatti',
        role: 'Expresidente Municipal de Coacalco / Exdiputado Federal',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 5, fiscalizacion: 16, funcionarios: 3, deuda: 15, denuncias: 6, evasion: 7, nepotismo: 3 },
        breakdown: {
            sentencias: 'Sin sentencias penales directas confirmadas.',
            fiscalizacion: 'OSFEM reportó pasivo de $640.7M. Endeudamiento 104.1%. Gastos financieros = 33% de ingresos.',
            funcionarios: 'No se documentaron detenciones directas.',
            deuda: 'Deuda per cápita: de $937 a $3,394. Tardarían 50 años en pagar.',
            denuncias: 'CONADE contradijo versión sobre devolución de $9.5M para estadio nunca construido.',
            evasion: 'Dejó alcaldía para buscar diputación federal con fuero.',
            nepotismo: 'No documentado con fuentes verificables.',
        },
        timeline: [
            { year: '2009', event: 'Asume presidencia municipal de Coacalco' },
            { year: '2012', event: 'Deja alcaldía. OSFEM reporta pasivo de $640.7M. Electo diputado federal.' },
        ],
        sources: [
            { label: 'OSFEM — Cuenta Pública 2012', url: 'https://www.osfem.gob.mx' },
        ],
    },
    {
        id: 3,
        name: 'Erwin Castelán Enríquez',
        role: 'Expresidente Municipal de Coacalco (2016-2018)',
        party: 'PRI',
        state: 'Estado de México',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 20, fiscalizacion: 12, funcionarios: 5, deuda: 10, denuncias: 6, evasion: 5, nepotismo: 2 },
        breakdown: {
            sentencias: 'SCJN ordenó destitución y consignación penal (enero 2018). Pena de 5-10 años.',
            fiscalizacion: 'Heredó y no resolvió deuda >$800M en laudos.',
            funcionarios: 'Cabildo completo destituido por la SCJN.',
            deuda: 'Laudos laborales y administrativos por >$800M sin resolver.',
            denuncias: 'Empresarios denunciaron maniobras para evadir embargos (amenazas de bomba simuladas).',
            evasion: 'Desacató sentencia de amparo reiteradamente.',
            nepotismo: 'No documentado.',
        },
        timeline: [
            { year: '2016', event: 'Asume presidencia municipal' },
            { year: '2018', event: 'SCJN destituye cabildo completo y ordena consignación' },
        ],
        sources: [
            { label: 'Proceso — SCJN', url: 'https://www.proceso.com.mx/nacional/2018/1/16/la-corte-destituye-consigna-alcaldes-cabildos-del-edomex-de-puebla-198309.html' },
            { label: 'El Universal — Adeudos', url: 'https://www.eluniversal.com.mx/metropoli/edomex/empresarios-acusan-adeudo-de-coacalco/' },
        ],
    },
];

// =====================================================
// NIVEL FEDERAL — FUNCIONARIOS DE ALTO NIVEL
// =====================================================

officials.push(
    {
        id: 301,
        name: 'Genaro García Luna',
        role: 'Exsecretario de Seguridad Pública Federal (2006-2012)',
        party: 'PAN',
        state: 'Federal',
        level: 'federal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 25, fiscalizacion: 18, funcionarios: 15, deuda: 15, denuncias: 10, evasion: 5, nepotismo: 5 },
        breakdown: {
            sentencias: 'Sentenciado a 38 años y 8 meses de prisión en EE.UU. (octubre 2024). Culpable de empresa criminal continua, conspiración para importar cocaína y declaraciones falsas. Multa de $2M USD.',
            fiscalizacion: 'Aceptó millones de dólares en sobornos del Cártel de Sinaloa. Facilitó importación de más de un millón de kg de estupefacientes a EE.UU.',
            funcionarios: 'Red de protección policial al Cártel de Sinaloa desde la Policía Federal. Múltiples mandos involucrados.',
            deuda: 'Sobornos millonarios del Cártel de Sinaloa. Propiedades y cuentas en EE.UU. Mintió en solicitud de naturalización.',
            denuncias: 'Más de 20 testigos cooperantes (exjefes de cárteles) declararon en su contra. Caso documentado por DOJ, DEA, CNN, Univision.',
            evasion: 'Intentó naturalizarse estadounidense mintiendo sobre antecedentes. Detenido en Texas en 2019.',
            nepotismo: 'Filtró información confidencial al Cártel. Utilizó la Policía Federal para atacar rivales del Cártel de Sinaloa.',
        },
        timeline: [
            { year: '2001', event: 'Director de la Agencia Federal de Investigación (AFI)' },
            { year: '2006', event: 'Secretario de Seguridad Pública bajo Felipe Calderón' },
            { year: '2012', event: 'Termina cargo. Se muda a EE.UU.' },
            { year: '2019', event: 'Detenido en Texas por la DEA' },
            { year: '2023', event: 'Declarado culpable por jurado en Brooklyn' },
            { year: '2024', event: 'Sentenciado a 38 años y 8 meses de prisión' },
        ],
        sources: [
            { label: 'DOJ — Sentencia oficial', url: 'https://www.justice.gov/es/usao-edny/pr/ex-secretario-de-seguridad-publica-mexicana-genaro-garcia-luna-condenado-mas-de-38' },
            { label: 'CNN — Condena', url: 'https://cnnespanol.cnn.com/2024/10/16/garcia-luna-sentencia-38-orix/' },
        ],
    },
    {
        id: 302,
        name: 'Emilio Lozoya Austin',
        role: 'Exdirector de Pemex (2012-2016)',
        party: 'PRI',
        state: 'Federal',
        level: 'federal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 20, fiscalizacion: 20, funcionarios: 12, deuda: 15, denuncias: 10, evasion: 7, nepotismo: 5 },
        breakdown: {
            sentencias: 'Vinculado a proceso por lavado de dinero, asociación delictuosa y cohecho (caso Odebrecht). Proceso penal abierto por caso Agronitrogenados. SCJN dejó firme sentencia por daño moral (marzo 2026).',
            fiscalizacion: 'Caso Odebrecht: recibió $10.5M USD en sobornos de la constructora brasileña. Caso Agronitrogenados: compra de planta de fertilizantes por $275M USD (planta inoperante 14 años, sobreprecio masivo).',
            funcionarios: 'Su hermana Gilda Lozoya detenida. René Gavira (caso Segalmex) vinculado. Red de operadores financieros.',
            deuda: 'Daño patrimonial a Pemex por cientos de millones de dólares. Residencia de $51M MXN decomisada por FGR (mayo 2026).',
            denuncias: 'Caso emblema de corrupción del sexenio Peña Nieto. Documentado por ASF, FGR, TOJIL, medios internacionales.',
            evasion: 'Prófugo. Detenido en Málaga, España (2020). Extraditado. Buscó criterio de oportunidad como testigo colaborador. Prisión domiciliaria desde 2024.',
            nepotismo: 'Propiedades familiares adquiridas con recursos ilícitos. Operaciones a través de familiares y prestanombres.',
        },
        timeline: [
            { year: '2012', event: 'Nombrado director de Pemex por Peña Nieto' },
            { year: '2014', event: 'Compra de Agronitrogenados por $275M USD a sobreprecio' },
            { year: '2017', event: 'Caso Odebrecht estalla internacionalmente' },
            { year: '2020', event: 'Detenido en Málaga, España. Extraditado a México.' },
            { year: '2021', event: 'Ingresado a Reclusorio Norte por riesgo de fuga' },
            { year: '2024', event: 'Prisión domiciliaria con brazalete electrónico' },
            { year: '2026', event: 'SCJN ratifica sentencia. FGR decomisa residencia de $51M.' },
        ],
        sources: [
            { label: 'La Jornada — SCJN', url: 'https://www.jornada.com.mx/noticia/2026/03/04/politica/scjn-deja-firme-primera-sentencia-contra-lozoya-por-acusaciones-en-caso-odebrecht' },
            { label: 'Infobae — Decomiso residencia', url: 'https://www.infobae.com/mexico/2026/05/09/caso-lozoya-fgr-logra-quitarle-residencia-de-51-millones-de-pesos-en-la-cdmx-al-exdirector-de-pemex/' },
            { label: 'TOJIL — Seguimiento', url: 'https://tojil.org/en/emilio-lozoya-y-el-caso-odebrecht/' },
        ],
    },
    {
        id: 303,
        name: 'Ignacio Ovalle Fernández',
        role: 'Exdirector de Segalmex (2019-2022)',
        party: 'MORENA',
        state: 'Federal',
        level: 'federal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 8, fiscalizacion: 20, funcionarios: 14, deuda: 15, denuncias: 10, evasion: 8, nepotismo: 5 },
        breakdown: {
            sentencias: 'SIN INVESTIGACIÓN PENAL NI ADMINISTRATIVA a pesar de dirigir Segalmex durante el desfalco. 26 personas vinculadas a proceso pero Ovalle NO ha sido imputado.',
            fiscalizacion: 'ASF detectó desvío de $15,000M. Desfalco más grande del sexenio AMLO. Pagos a empresas fantasma, faltantes de granos, contratos sin entrega de bienes, certificados bursátiles por $700M sin autorización.',
            funcionarios: '26 personas vinculadas a proceso (9 servidores públicos, 17 particulares). 47 órdenes de aprehensión. René Gavira (director de Finanzas) con 7 imputaciones por más de $2,639M.',
            deuda: 'Desfalco al erario por entre $9,500M y $15,000M según diferentes cálculos oficiales. AMLO reconoció que fue "lo más doloroso" de su gobierno.',
            denuncias: 'Documentado por Mexicanos Contra la Corrupción, ASF, Reforma, El Universal. AMLO lo exculpó públicamente.',
            evasion: 'No fue procesado. Fue PREMIADO con otro cargo (INAFED). SCJN determinó que peculado prescribe, lo que podría blindarlo permanentemente.',
            nepotismo: 'Recomendó funcionarios "priistas de malas mañas" según AMLO. Denominador común: también dirigió Conasupo en los 90 cuando hubo desfalco de $18,953M.',
        },
        timeline: [
            { year: '1988', event: 'Director de Conasupo. Desfalco de 1.6 billones de viejos pesos.' },
            { year: '2019', event: 'Nombrado director de Segalmex por AMLO' },
            { year: '2020', event: 'ASF detecta irregularidades por $15,000M' },
            { year: '2022', event: 'Relevado de Segalmex. Enviado al INAFED como "premio".' },
            { year: '2023', event: '22 órdenes de aprehensión. Ovalle NO incluido.' },
            { year: '2026', event: 'SCJN determina que peculado prescribe. Ovalle deja INAFED.' },
        ],
        sources: [
            { label: 'El Universal — Impunidad', url: 'https://www.eluniversal.com.mx/nacion/ovalle-desaparece-del-gobierno-como-los-15-mil-mdp-de-segalmex/' },
            { label: 'Grupo Animal — Sin investigación', url: 'https://grupoanimal.mx/politica/segalmex-exdirector-ignacio-ovalle-sin-investigacion-desvios' },
            { label: 'Meganoticias — Saqueo impune', url: 'https://www.meganoticias.mx/cdmx/noticia/segalmex-el-saqueo-impune/740624' },
        ],
    },
    {
        id: 304,
        name: 'Rosario Robles Berlanga',
        role: 'Exsecretaria de Desarrollo Social y SEDATU (2012-2018)',
        party: 'PRI',
        state: 'Federal',
        level: 'federal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 19, funcionarios: 10, deuda: 14, denuncias: 9, evasion: 4, nepotismo: 4 },
        breakdown: {
            sentencias: 'Procesada por ejercicio indebido del servicio público (Estafa Maestra). Presa en Santa Martha Acatitla (2019-2022). Criterio de oportunidad como testigo colaborador.',
            fiscalizacion: 'Estafa Maestra: $7,670M desviados a través de 11 dependencias y universidades públicas que subcontrataron empresas fantasma para servicios nunca realizados.',
            funcionarios: 'Red de funcionarios de Sedesol y SEDATU involucrados en la triangulación de recursos.',
            deuda: 'Daño al erario de $7,670M del esquema Estafa Maestra.',
            denuncias: 'Investigación periodística de Animal Político y MCCI. Documentado por ASF.',
            evasion: 'Se entregó voluntariamente. Negoció criterio de oportunidad.',
            nepotismo: 'Red de universidades como intermediarias para canalizar recursos a empresas fantasma.',
        },
        timeline: [
            { year: '2012', event: 'Secretaria de Desarrollo Social bajo Peña Nieto' },
            { year: '2015', event: 'Titular de SEDATU' },
            { year: '2019', event: 'Detenida por Estafa Maestra. Presa en Santa Martha.' },
            { year: '2022', event: 'Liberada. Criterio de oportunidad como testigo.' },
        ],
        sources: [
            { label: 'Animal Político — Estafa Maestra', url: 'https://www.animalpolitico.com/estafa-maestra/' },
        ],
    },
    // =====================================================
    // MÁS EXGOBERNADORES
    // =====================================================
    {
        id: 117,
        name: 'Guillermo Padrés Elías',
        role: 'Exgobernador de Sonora (2009-2015)',
        party: 'PAN',
        state: 'Sonora',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 17, fiscalizacion: 15, funcionarios: 7, deuda: 12, denuncias: 8, evasion: 5, nepotismo: 4 },
        breakdown: {
            sentencias: 'Procesado por lavado de dinero y defraudación fiscal. Preso en el Reclusorio Norte.',
            fiscalizacion: 'Señalamientos de desvío de recursos del gobierno de Sonora.',
            funcionarios: 'Excolaboradores investigados por irregularidades financieras.',
            deuda: 'Acumulación de propiedades y riqueza inexplicable. Defraudación fiscal documentada.',
            denuncias: 'Documentado por medios nacionales y la administración sucesora.',
            evasion: 'Enfrentó proceso pero estuvo preso.',
            nepotismo: 'Propiedades a nombre de familiares y prestanombres.',
        },
        timeline: [
            { year: '2009', event: 'Asume gubernatura de Sonora' },
            { year: '2016', event: 'Detenido por lavado de dinero y defraudación fiscal' },
        ],
        sources: [
            { label: 'Proceso', url: 'https://www.proceso.com.mx' },
        ],
    },
    {
        id: 118,
        name: 'Humberto Moreira Valdés',
        role: 'Exgobernador de Coahuila (2005-2011) / Expresidente del PRI',
        party: 'PRI',
        state: 'Coahuila',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 14, fiscalizacion: 20, funcionarios: 10, deuda: 15, denuncias: 10, evasion: 8, nepotismo: 4 },
        breakdown: {
            sentencias: 'Detenido brevemente en España en 2016 por lavado de dinero. Liberado. No ha sido procesado en México de forma efectiva.',
            fiscalizacion: 'Megadeuda de Coahuila: endeudó al estado en más de $36,000M de pesos de forma irregular, falsificando documentos y sin aprobación del Congreso.',
            funcionarios: 'Su hermano Rubén Moreira asumió la gubernatura. Jorge Torres López (sustituto) prófugo de la DEA. Red familiar y política.',
            deuda: 'Megadeuda de $36,000M que hipotecó a Coahuila por décadas. Fondos canalizados a paraísos fiscales y bancos en Texas.',
            denuncias: 'Caso emblemático documentado por Proceso, NYT, medios internacionales. Investigaciones de la DEA.',
            evasion: 'Detenido en España y liberado. No ha enfrentado justicia efectiva en México.',
            nepotismo: 'Presidente nacional del PRI. Su hermano lo sucedió como gobernador. Red familiar de control estatal.',
        },
        timeline: [
            { year: '2005', event: 'Asume gubernatura de Coahuila' },
            { year: '2011', event: 'Presidente nacional del PRI. Estalla escándalo de megadeuda.' },
            { year: '2016', event: 'Detenido brevemente en España. Liberado.' },
        ],
        sources: [
            { label: 'Proceso — Megadeuda', url: 'https://www.proceso.com.mx' },
        ],
    },
    {
        id: 119,
        name: 'Jesús Reyna García',
        role: 'Exgobernador interino de Michoacán (2013)',
        party: 'PRI',
        state: 'Michoacán',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 18, fiscalizacion: 8, funcionarios: 6, deuda: 6, denuncias: 9, evasion: 4, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido en 2014 y arraigado por la PGR. Acusado de proteger al cártel de los Caballeros Templarios. Preso 4 años 8 meses sin juicio. PGR desistió en 2018.',
            fiscalizacion: 'Señalamientos de protección estatal al crimen organizado.',
            funcionarios: 'Red gubernamental de protección a Los Caballeros Templarios.',
            deuda: 'Corrupción por protección al narcotráfico más que por desvío directo.',
            denuncias: 'Acusado de reunirse con Nazario Moreno "El Chayo" y Servando Gómez "La Tuta".',
            evasion: 'Preso sin sentencia durante casi 5 años.',
            nepotismo: 'Red de protección gubernamental al crimen organizado.',
        },
        timeline: [
            { year: '2013', event: 'Gobernador interino de Michoacán' },
            { year: '2014', event: 'Detenido por vínculos con Caballeros Templarios' },
            { year: '2018', event: 'PGR desiste de acusaciones. Liberado.' },
        ],
        sources: [
            { label: 'Semanario ZETA', url: 'https://zetatijuana.com' },
        ],
    },
    {
        id: 120,
        name: 'Silvano Aureoles Conejo',
        role: 'Exgobernador de Michoacán (2015-2021)',
        party: 'PRD',
        state: 'Michoacán',
        level: 'estatal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 12, fiscalizacion: 16, funcionarios: 7, deuda: 13, denuncias: 9, evasion: 6, nepotismo: 3 },
        breakdown: {
            sentencias: 'Bajo investigación por desvío de miles de millones. SCJN determinó que peculado prescribe, lo que podría beneficiarlo.',
            fiscalizacion: 'Señalamientos de desvío masivo de recursos del gobierno de Michoacán. Deuda pública estatal incrementada.',
            funcionarios: 'Funcionarios investigados por irregularidades financieras.',
            deuda: 'Desvío de miles de millones de pesos del erario michoacano.',
            denuncias: '37 denuncias ante la FGR por irregularidades en manejo de recursos en Tabasco (nota: referencia cruzada con otros políticos señalados).',
            evasion: 'Ha evitado proceso efectivo hasta ahora.',
            nepotismo: 'Señalamientos de contratos dirigidos.',
        },
        timeline: [
            { year: '2015', event: 'Asume gubernatura de Michoacán' },
            { year: '2021', event: 'Termina mandato bajo señalamientos de corrupción' },
            { year: '2026', event: 'SCJN: peculado prescribe. Podría beneficiarse.' },
        ],
        sources: [
            { label: 'Red Michoacán', url: 'https://www.redmichoacan.com' },
        ],
    },
    // =====================================================
    // MÁS OPERACIÓN ENJAMBRE
    // =====================================================
    {
        id: 209,
        name: 'Uruviel González Vieyra',
        role: 'Alcalde de Quimixtlán, Puebla',
        party: 'MORENA',
        state: 'Puebla',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 17, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 7, evasion: 3, nepotismo: 5 },
        breakdown: {
            sentencias: 'Detenido el 7 de marzo 2025 por vínculos con organizaciones delictivas.',
            fiscalizacion: 'Bajo investigación federal por irregularidades.',
            funcionarios: 'Hermano de Giovanni (Tlachichuca) y Ramiro (San Nicolás). Red familiar de control.',
            deuda: 'Presunta canalización de recursos hacia actividades ilícitas.',
            denuncias: 'Investigación federal por delincuencia organizada.',
            evasion: 'No evadió detención.',
            nepotismo: 'TRES HERMANOS gobernando municipios simultáneamente en Puebla. Red familiar.',
        },
        timeline: [
            { year: '2025', event: 'Detenido en Operación Enjambre junto con hermanos' },
        ],
        sources: [
            { label: 'Infobae — Enjambre Puebla', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 210,
        name: 'Ramiro González Vieyra',
        role: 'Alcalde de San Nicolás Buenos Aires, Puebla',
        party: 'MORENA',
        state: 'Puebla',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 16, fiscalizacion: 6, funcionarios: 8, deuda: 5, denuncias: 7, evasion: 3, nepotismo: 5 },
        breakdown: {
            sentencias: 'Detenido el 29 de mayo 2025 por vínculos con organizaciones delictivas.',
            fiscalizacion: 'Bajo investigación federal.',
            funcionarios: 'Tercer hermano González Vieyra detenido. Incluido en expedientes de delincuencia organizada.',
            deuda: 'Red familiar de control municipal con presunta actividad ilícita.',
            denuncias: 'Investigación federal documentada.',
            evasion: 'No evadió detención.',
            nepotismo: 'Hermano de Giovanni y Uruviel. Control familiar de tres municipios poblanos.',
        },
        timeline: [
            { year: '2025', event: 'Detenido como tercer hermano en Operación Enjambre' },
        ],
        sources: [
            { label: 'Infobae — Enjambre', url: 'https://www.infobae.com' },
        ],
    },
    {
        id: 211,
        name: 'José Ascención "N"',
        role: 'Alcalde de Teuchitlán, Jalisco',
        party: 'Sin dato',
        state: 'Jalisco',
        level: 'municipal',
        active: false, status: 'ex_funcionario',
        scores: { sentencias: 15, fiscalizacion: 6, funcionarios: 6, deuda: 5, denuncias: 7, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Detenido por presuntos vínculos criminales en el marco de Operación Enjambre.',
            fiscalizacion: 'Bajo investigación federal.',
            funcionarios: 'Su hermano también fue detenido posteriormente, vinculado a robo de combustible.',
            deuda: 'Señalamientos de actividades ilícitas desde el gobierno municipal.',
            denuncias: 'Sheinbaum lo mencionó como ejemplo de la estrategia Enjambre.',
            evasion: 'No evadió detención.',
            nepotismo: 'Hermano vinculado a robo de combustible (huachicol).',
        },
        timeline: [
            { year: '2025', event: 'Detenido en Operación Enjambre en Jalisco' },
        ],
        sources: [
            { label: 'Grupo Animal — Enjambre', url: 'https://grupoanimal.mx/seguridad/operativo-enjambre-alcaldes-funcionarios-corrupcion-delincuencia' },
        ],
    }
);

// =====================================================
// ESTADÍSTICAS NACIONALES (para el hero)
// =====================================================
const NATIONAL_STATS = {
    totalOfficials: officials.length,
    totalStates: new Set(officials.map(o => o.state)).size,
    activeOfficials: officials.filter(o => o.active).length,
    criticalLevel: officials.filter(o => {
        const total = Object.values(o.scores).reduce((a, b) => a + b, 0);
        return total >= 75;
    }).length,
    enjambreDetentions: 147,
    enjambreSentenceYears: 878,
    lastUpdate: '2026-07-14',
};

// =====================================================
// CANDIDATOS JUDICIALES CON SEÑALAMIENTOS (Elección 2025)
// =====================================================
officials.push(
    {
        id: 401,
        name: 'Leopoldo Chávez',
        role: 'Candidato a Magistrado del Tribunal Colegiado, Durango',
        party: 'Sin partido',
        state: 'Durango',
        level: 'federal',
        active: true, status: 'en_funciones',
        status: 'candidato',
        scores: { sentencias: 20, fiscalizacion: 3, funcionarios: 3, deuda: 3, denuncias: 8, evasion: 3, nepotismo: 2 },
        breakdown: {
            sentencias: 'Condenado a más de 5 años de prisión en EE.UU. por intento de venta de más de 4 kg de metanfetaminas.',
            fiscalizacion: 'Sin señalamientos de fiscalización.',
            funcionarios: 'Sin red documentada.',
            deuda: 'Antecedentes penales por narcotráfico.',
            denuncias: 'Documentado por Reuters, Defensorxs, CNN. Perfil "altamente riesgoso" según ONG.',
            evasion: 'Cumplió condena en EE.UU.',
            nepotismo: 'Escasa experiencia judicial (3 años no vinculados al ámbito judicial).',
        },
        timeline: [
            { year: '2020', event: 'Condenado en EE.UU. por delitos de metanfetaminas' },
            { year: '2025', event: 'Postulado como candidato a magistrado en Durango' },
        ],
        sources: [
            { label: 'Reuters — Antecedentes', url: 'https://www.reuters.com' },
            { label: 'Defensorxs — Justicia en la Mira', url: 'https://pijamasurf.com/2025/05/justicia_en_riesgo_los_perfiles_mas_cuestionables_rumbo_al_poder_judicial/' },
        ],
    },
    {
        id: 402,
        name: 'Silvia Rocío Delgado',
        role: 'Candidata a Jueza Penal, Chihuahua',
        party: 'Sin partido',
        state: 'Chihuahua',
        level: 'federal',
        active: true, status: 'en_funciones',
        status: 'candidato',
        scores: { sentencias: 5, fiscalizacion: 2, funcionarios: 3, deuda: 2, denuncias: 8, evasion: 2, nepotismo: 4 },
        breakdown: {
            sentencias: 'Sin sentencias penales propias.',
            fiscalizacion: 'Sin señalamientos directos.',
            funcionarios: 'Formó parte del equipo jurídico del Chapo Guzmán. Enlace directo para amparos.',
            deuda: 'Sin daño patrimonial documentado.',
            denuncias: 'Señalada por Defensorxs, Infobae, CNN y El Español. Cuestionamientos éticos graves por defender al líder del Cártel de Sinaloa.',
            evasion: 'Sin evasión de justicia.',
            nepotismo: 'Vínculos profesionales directos con el Cártel de Sinaloa a través de defensa legal.',
        },
        timeline: [
            { year: '2016', event: 'Abogada defensora de Joaquín "El Chapo" Guzmán' },
            { year: '2025', event: 'Candidata a jueza penal en Chihuahua' },
        ],
        sources: [
            { label: 'Infobae — Candidaturas riesgosas', url: 'https://www.infobae.com/mexico/2025/04/17/rumbo-al-poder-judicial-ongs-identifican-al-menos-13-candidaturas-con-antecedentes-turbios/' },
        ],
    },
    {
        id: 403,
        name: 'Francisco Hernández Zaragoza',
        role: 'Candidato a Magistrado Penal, Jalisco',
        party: 'Sin partido',
        state: 'Jalisco',
        level: 'federal',
        active: true, status: 'en_funciones',
        status: 'candidato',
        scores: { sentencias: 12, fiscalizacion: 5, funcionarios: 3, deuda: 3, denuncias: 9, evasion: 3, nepotismo: 3 },
        breakdown: {
            sentencias: 'Destituido como juez en 2015 por el Consejo de la Judicatura Federal tras investigación por acoso sexual y corrupción.',
            fiscalizacion: 'Investigado por presuntos actos de corrupción y lavado de dinero durante gestión como juez penal.',
            funcionarios: 'Denuncias de personal del juzgado por violencia laboral y sexual.',
            deuda: 'Señalamientos de corrupción en resoluciones judiciales.',
            denuncias: 'Denuncia formal de trabajadora del Juzgado Sexto Penal por acoso sexual (2013). Documentado por SinEmbargo, Defensorxs.',
            evasion: 'Destituido pero sin consecuencias penales efectivas.',
            nepotismo: 'Reincidencia: postulado para magistratura pese a destitución previa.',
        },
        timeline: [
            { year: '2013', event: 'Denunciado por acoso sexual por trabajadora del juzgado' },
            { year: '2015', event: 'Destituido como juez por la Judicatura Federal' },
            { year: '2025', event: 'Candidato a Magistrado. Aprobado por Poder Legislativo.' },
        ],
        sources: [
            { label: 'SinEmbargo — Ganadores cuestionados', url: 'https://www.sinembargo.mx/4660660/varios-ganadores-en-la-eleccion-judicial-tienen-acusaciones-y-hasta-denuncias/' },
        ],
    },
    {
        id: 404,
        name: 'Madián Sinaí Menchaca Sierra',
        role: 'Candidata electa a Jueza, Jalisco',
        party: 'Sin partido',
        state: 'Jalisco',
        level: 'federal',
        active: true, status: 'en_funciones',
        status: 'candidato',
        scores: { sentencias: 8, fiscalizacion: 2, funcionarios: 3, deuda: 2, denuncias: 9, evasion: 2, nepotismo: 5 },
        breakdown: {
            sentencias: 'Detenida en Tlaquepaque por lesiones culposas (mayo 2024).',
            fiscalizacion: 'Sin señalamientos de fiscalización directos.',
            funcionarios: 'Vínculos con la secta La Luz del Mundo a través de su padre, el obispo Nicolás Menchaca.',
            deuda: 'Sin daño patrimonial directo.',
            denuncias: 'Hija del obispo Nicolás Menchaca, defensor legal de Naasón Joaquín García (líder de La Luz del Mundo sentenciado en EE.UU. por delitos sexuales contra menores). Víctimas denuncian que Menchaca ofreció dinero para silenciar denuncias.',
            evasion: 'Sin evasión documentada.',
            nepotismo: 'INE la declaró no elegible inicialmente pero TEPJF revocó y recibió constancia de mayoría. Nexos familiares con secta procesada por delitos sexuales.',
        },
        timeline: [
            { year: '2024', event: 'Detenida por lesiones culposas en Jalisco' },
            { year: '2025', event: 'INE la declara no elegible. TEPJF revoca. Recibe constancia.' },
        ],
        sources: [
            { label: 'Verificado — Candidaturas de alto riesgo', url: 'https://verificado.com.mx/eleccion-judicial-candidaturas-alto-riesgo/' },
        ],
    },
    {
        id: 405,
        name: 'Hortencia García Rodríguez',
        role: 'Candidata a Magistrada Penal, Chihuahua',
        party: 'Sin partido',
        state: 'Chihuahua',
        level: 'estatal',
        active: true, status: 'en_funciones',
        status: 'candidato',
        scores: { sentencias: 5, fiscalizacion: 5, funcionarios: 3, deuda: 3, denuncias: 8, evasion: 3, nepotismo: 5 },
        breakdown: {
            sentencias: 'Sin sentencias penales propias.',
            fiscalizacion: 'Cuestionada por resoluciones judiciales favorables a exgobernador César Duarte.',
            funcionarios: 'Ordenó la detención del exfiscal que procesaba a Duarte.',
            deuda: 'Señalamientos de uso del cargo para favorecer intereses políticos.',
            denuncias: 'Liberó a César Duarte sin audiencia formal para cambio de medida cautelar (2024). Ordenó detención del fiscal que investigaba a Duarte y a María Eugenia Campos.',
            evasion: 'Sin evasión propia.',
            nepotismo: 'Patrón de resoluciones judiciales que favorecen a actores políticos y obstaculizan la justicia.',
        },
        timeline: [
            { year: '2021', event: 'Ordena detención del fiscal de Operación Justicia para Chihuahua' },
            { year: '2024', event: 'Libera a César Duarte sin audiencia formal' },
            { year: '2025', event: 'Candidata a magistrada penal en Chihuahua' },
        ],
        sources: [
            { label: 'SinEmbargo — Ganadores cuestionados', url: 'https://www.sinembargo.mx/4660660/varios-ganadores-en-la-eleccion-judicial-tienen-acusaciones-y-hasta-denuncias/' },
        ],
    }
);


// =====================================================
// EXPANSION NACIONAL — JULIO 2026
// =====================================================
officials.push(
    {id:121,name:'Cuauhtémoc Blanco Bravo',role:'Exgobernador de Morelos (2018-2024)',party:'MORENA',state:'Morelos',level:'estatal',active:false,status:'ex_funcionario',
    scores:{sentencias:8,fiscalizacion:18,funcionarios:10,deuda:12,denuncias:10,evasion:5,nepotismo:5},
    breakdown:{sentencias:'4 denuncias penales por corrupción. Investigación por declaración patrimonial. Desafuero bloqueado por Morena (291 votos).',fiscalizacion:'$323M pagados a empresas fantasma que dejaron sin medicinas a 238 hospitales. ASF investiga miles de millones. Irregularidades en 17 secretarías y 44 organismos.',funcionarios:'Jefe de oficina investigado por UIF por lavado. Red de empresas de consejero de Morena. 23 denuncias encontradas en el cajón.',deuda:'Desvío de $40M en primer bloque. $323M a empresas fantasma. Saqueo aún no calculado.',denuncias:'Fotografiado 9 veces con líderes del CJNG y Comando Tlahuica. Animal Político documentó red de empresas.',evasion:'Diputado federal con fuero. Desafuero bloqueado.',nepotismo:'Medio hermano Ulises Bravo líder de Morena. Empresas de familiares con contratos. Secretario particular vinculado a empresa del gobernador.'},
    timeline:[{year:'2018',event:'Asume gubernatura'},{year:'2022',event:'Fotografiado con líderes del CJNG'},{year:'2024',event:'Sucesora denuncia saqueo generalizado'},{year:'2025',event:'4 denuncias penales. Desafuero bloqueado.'}],
    sources:[{label:'Animal Político',url:'https://grupoanimal.mx/politica/corrupcion-morelos-cuauhtemoc-blanco-medicamentos'},{label:'Proceso',url:'https://www.proceso.com.mx/nacional/estados/2025/1/14/denuncian-corrupcion-generalizada-en-el-gobierno-de-cuauhtemoc-blanco-343742.html'}]},
    {id:212,name:'Ernesto Cruz Díaz',role:'Alcalde de Cintalapa, Chiapas',party:'MORENA',state:'Chiapas',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:18,fiscalizacion:10,funcionarios:6,deuda:8,denuncias:8,evasion:3,nepotismo:3},
    breakdown:{sentencias:'Detenido enero 2026 por abuso de autoridad, corrupción y malversación.',fiscalizacion:'Desvío de fondos municipales.',funcionarios:'Protección y aviso de operativos al Cártel Chiapas-Guatemala y CJNG.',deuda:'Malversación de recursos públicos.',denuncias:'Reelecto pese a señalamientos. Documentado por Nación321.',evasion:'No evadió.',nepotismo:'4 años en cargo con señalamientos.'},
    timeline:[{year:'2021',event:'Primera gestión'},{year:'2024',event:'Reelecto por Morena'},{year:'2026',event:'Detenido'}],
    sources:[{label:'Nación321',url:'https://www.nacion321.com/seguridad/2026/02/09/sin-impunidad-mas-de-la-mitad-de-los-alcaldes-detenidos-en-el-sexenio-son-morenistas/'}]},
    {id:213,name:'Rosember López',role:'Alcalde de Bellavista, Chiapas',party:'Chiapas Unido',state:'Chiapas',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:15,fiscalizacion:5,funcionarios:5,deuda:4,denuncias:7,evasion:3,nepotismo:2},
    breakdown:{sentencias:'Detenido 2025 por vínculos con crimen organizado.',fiscalizacion:'Bajo investigación federal.',funcionarios:'Red de protección criminal.',deuda:'Sin datos específicos.',denuncias:'Lista de alcaldes detenidos.',evasion:'No evadió.',nepotismo:'Sin datos.'},
    timeline:[{year:'2025',event:'Detenido por vínculos criminales'}],
    sources:[{label:'El Universal',url:'https://www.eluniversal.com.mx/estados/alcaldes-y-exalcaldes-bajo-la-lupa-por-vinculos-con-el-crimen-organizado-reforma-busca-frenar-candidatos-con-nexos-delictivos/'}]},
    {id:214,name:'José Antonio "N"',role:'Alcalde de Frontera Comalapa, Chiapas',party:'Sin dato',state:'Chiapas',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:19,fiscalizacion:6,funcionarios:7,deuda:5,denuncias:9,evasion:3,nepotismo:3},
    breakdown:{sentencias:'Detenido por desaparición forzada, homicidio, extorsión y nexos criminales.',fiscalizacion:'Bajo investigación por múltiples delitos.',funcionarios:'Red de protección en zona fronteriza.',deuda:'Extorsión como financiamiento.',denuncias:'Cargos graves: desaparición forzada y homicidio.',evasion:'No evadió.',nepotismo:'Control criminal de municipio fronterizo.'},
    timeline:[{year:'2025',event:'Detenido por desaparición forzada, homicidio y nexos criminales'}],
    sources:[{label:'La Razón',url:'https://www.razon.com.mx/mexico/2026/02/07/caen-35-alcaldes-en-seis-anos-por-vinculos-con-la-actividad-criminal/'}]},
    {id:215,name:'Plácido Martínez Soler',role:'Alcalde de San Juan Mazatlán, Oaxaca',party:'MORENA',state:'Oaxaca',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:20,fiscalizacion:4,funcionarios:3,deuda:3,denuncias:9,evasion:5,nepotismo:3},
    breakdown:{sentencias:'Detenido oct 2024 por falsificación de documentos para evadir imputación por violación de menor (2013).',fiscalizacion:'Sin señalamientos específicos.',funcionarios:'Esposa también detenida.',deuda:'Sin daño patrimonial específico.',denuncias:'Imputado por violación equiparada contra adolescente.',evasion:'Falsificó documentos para evadir imputación.',nepotismo:'Esposa involucrada en encubrimiento.'},
    timeline:[{year:'2013',event:'Imputado por violación equiparada contra menor'},{year:'2024',event:'Detenido junto con esposa'}],
    sources:[{label:'Nación321',url:'https://www.nacion321.com/seguridad/2026/02/09/sin-impunidad-mas-de-la-mitad-de-los-alcaldes-detenidos-en-el-sexenio-son-morenistas/'}]},
    {id:216,name:'Mauro Yuriel Jáuregui Muñoz',role:'Alcalde de Apulco, Zacatecas',party:'MC',state:'Zacatecas',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:16,fiscalizacion:5,funcionarios:5,deuda:5,denuncias:7,evasion:3,nepotismo:3},
    breakdown:{sentencias:'Desaforado y detenido en 2025.',fiscalizacion:'Bajo investigación federal.',funcionarios:'Red de protección criminal.',deuda:'Vinculado a actividades delictivas.',denuncias:'Lista de alcaldes con vínculos criminales.',evasion:'Desaforado antes de detención.',nepotismo:'Sin datos.'},
    timeline:[{year:'2025',event:'Desaforado y detenido por vínculos criminales'}],
    sources:[{label:'Mural Sonorense',url:'https://muralsonorense.com/alcaldes-y-exalcaldes-bajo-la-lupa-reforma-busca-frenar-candidatos-con-nexos-delictivos/'}]},
    {id:217,name:'Tania Vanessa Flores Guerra',role:'Exalcaldesa de Múzquiz, Coahuila',party:'PT',state:'Coahuila',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:14,fiscalizacion:12,funcionarios:4,deuda:8,denuncias:7,evasion:3,nepotismo:3},
    breakdown:{sentencias:'Detenida 2026 por corrupción durante gestión 2021-2024.',fiscalizacion:'ASEC documentó irregularidades.',funcionarios:'Sin datos de red.',deuda:'Actos de corrupción documentados.',denuncias:'ASEC presentó denuncias ante Fiscalía.',evasion:'No evadió.',nepotismo:'Sin datos.'},
    timeline:[{year:'2021',event:'Asume alcaldía por PT'},{year:'2026',event:'Detenida por corrupción'}],
    sources:[{label:'Localeando',url:'https://www.localeando.com/2026/07/coahuila-y-la-detencion-de-alcaldesas-y.html'}]},
    {id:218,name:'Ramiro Pérez Arciniega',role:'Exalcalde de Parras, Coahuila',party:'Oposición',state:'Coahuila',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:14,fiscalizacion:10,funcionarios:3,deuda:7,denuncias:6,evasion:3,nepotismo:2},
    breakdown:{sentencias:'Detenido enero 2023 por malos manejos.',fiscalizacion:'ASEC detectó irregularidades.',funcionarios:'Sin datos.',deuda:'Malos manejos de recursos.',denuncias:'Fiscalía Anticorrupción procesó caso.',evasion:'No evadió.',nepotismo:'Sin datos.'},
    timeline:[{year:'2023',event:'Detenido por malos manejos'}],
    sources:[{label:'Localeando',url:'https://www.localeando.com/2026/07/coahuila-y-la-detencion-de-alcaldesas-y.html'}]},
    {id:219,name:'Gerardo García Castillo',role:'Exalcalde de Monclova, Coahuila',party:'Oposición',state:'Coahuila',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:14,fiscalizacion:10,funcionarios:3,deuda:7,denuncias:6,evasion:3,nepotismo:2},
    breakdown:{sentencias:'Detenido enero 2023 por irregularidades.',fiscalizacion:'ASEC documentó malos manejos.',funcionarios:'Sin datos.',deuda:'Malos manejos de recursos.',denuncias:'Fiscalía Anticorrupción procesó caso.',evasion:'No evadió.',nepotismo:'Sin datos.'},
    timeline:[{year:'2023',event:'Detenido por irregularidades'}],
    sources:[{label:'Localeando',url:'https://www.localeando.com/2026/07/coahuila-y-la-detencion-de-alcaldesas-y.html'}]},
    {id:220,name:'Jorge Fabián "N"',role:'Alcalde de Lerdo de Tejada, Veracruz',party:'Sin dato',state:'Veracruz',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:18,fiscalizacion:5,funcionarios:4,deuda:4,denuncias:7,evasion:3,nepotismo:2},
    breakdown:{sentencias:'Detenido 2020. Preso en penal federal de Durango por secuestro agravado.',fiscalizacion:'Sin datos específicos.',funcionarios:'Sin red documentada.',deuda:'Secuestro agravado desde cargo.',denuncias:'Documentado por La Razón.',evasion:'No evadió.',nepotismo:'Sin datos.'},
    timeline:[{year:'2020',event:'Detenido por secuestro agravado'}],
    sources:[{label:'La Razón',url:'https://www.razon.com.mx/mexico/2026/02/07/caen-35-alcaldes-en-seis-anos-por-vinculos-con-la-actividad-criminal/'}]},
    {id:221,name:'Artemio Moriya Sánchez',role:'Alcalde de Tacámbaro, Michoacán',party:'Sin dato',state:'Michoacán',level:'municipal',active:false,status:'ex_funcionario',
    scores:{sentencias:10,fiscalizacion:5,funcionarios:5,deuda:5,denuncias:8,evasion:3,nepotismo:4},
    breakdown:{sentencias:'Señalado en informe SEDENA (sept 2021) por vínculos con crimen organizado.',fiscalizacion:'Parte de 29 alcaldes michoacanos señalados por SEDENA.',funcionarios:'Hija detenida en Texas con $250K USD y armas (2022).',deuda:'Vinculación con CJNG por inteligencia militar.',denuncias:'Informe clasificado de SEDENA. Detención de hija confirmó nexos.',evasion:'No detenido directamente.',nepotismo:'Hija transportando dinero y armas del narcotráfico.'},
    timeline:[{year:'2021',event:'SEDENA lo señala entre 29 alcaldes'},{year:'2022',event:'Hija detenida en Texas con $250K USD'}],
    sources:[{label:'La Razón',url:'https://www.razon.com.mx/mexico/2026/02/07/caen-35-alcaldes-en-seis-anos-por-vinculos-con-la-actividad-criminal/'}]}
);
